### ISSUE TITLE
Document aws_dimension_select_regex in README

### ISSUE THREAD

**Issue by marceldegraaf** [prometheus/cloudwatch_exporter#10]
I was looking for a way to export CloudWatch metrics for a subset of our DynamoDB tables to Prometheus. I had almost given up on this official exporter because it seemed like it could not do that, until I found out about `aws_dimension_select_regex` by reading the source code.

This is how I now fetch CloudWatch metrics for our production DynamoDB tables:

``` json
{
  "region": "us-east-1",
  "metrics": [
    {
      "aws_namespace": "AWS/DynamoDB",
      "aws_metric_name": "ProvisionedReadCapacityUnits",
      "aws_dimensions": [
        "TableName"
      ],
      "aws_dimension_select_regex": {
        "TableName": [ "(.*)_production" ]
      }
    }
  ]
}
```

It would be sweet if `aws_dimension_select_regex` was mentioned in the README.

**Comment by brian-brazil** [comment]
Thanks for the report, fixed in https://github.com/prometheus/cloudwatch_exporter/commit/6f76fa63128200fbd0c3e1804370d106007a80b2
