### ISSUE TITLE
exporter takes 4 minutes to return metrics

### ISSUE THREAD

**Issue by cristifalcas** [prometheus/cloudwatch_exporter#122]
Hello,

In the last days, cloudwatch exporter takes 4 minutes to retrieve all the metrics I request. At the beginning it was around 40 seconds, but that value grow in the last days to 4 minutes now:

```
# time curl localhost:9106/metrics| grep -v "^#" | sort | uniq | wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  667k    0  667k    0     0   2949      0 --:--:--  0:03:51 --:--:--  195k
4737

real	3m51.929s
user	0m0.016s
sys	0m0.048s
```

The only thing that I can think of that is strange in my case is that I've put "set_timestamp: false" globally.

But that should affect anything.

Any idea what is happening?

Also the application is taking a loong time to respond to requests. Does it do any retrieval at start?

Best regards,

**Comment by cristifalcas** [comment]
I can't find the source at all.

But I have another question, if possible.

CW_exporter says it did ~26k requests total. And in the output there are ~4.7k metrics. Why the difference. It looks like for every metric it does ~5.5k calls?

**Comment by brian-brazil** [comment]
That'd be expected if you're doing filtering, or have made more than one request to the exporter.
