### ISSUE TITLE
Question about scraping multiple accounts

### ISSUE THREAD

**Issue by lamont** [prometheus/cloudwatch_exporter#123]
We are attempting to use cloudwatch_exporter to pull cloudwatch metrics from about 200 accounts and I think I don't quite understand how the role_arn is supposed to work. I had hoped we could create a single IAM role with access to cloudwatch from each account, but when we do that, we're only getting cloudwatch metrics from one. Right now we're running multiple cloudwatch_exporters, one per account, with an account-specific role_arn per config file.

Is what I described, one cloudwatch_exporter per watched account, the right way to go? Is there a way to run a single cloudwatch_exporter process that can use multiple roles, or any way to get metrics from multiple accounts?

Thank you.

**Comment by brian-brazil** [comment]
You will need one exporter per account.

**Comment by lamont** [comment]
Would you entertain a PR allowing for each MetricRule to optionally specify a role_arn to be used for those requests? I think we'd maintain a map of activeConfig objects, one labeled "default", extend every loadConfig to use that map of clients, creating a new one every time it finds a new role_arn in a metricrule.  Then during the scrape, every request would either use config.client.get("default") or use the per-metric/job client. 

I'd also appreciate any direction if you think the above is the wrong approach.

**Comment by brian-brazil** [comment]
I don't think that'd work out, as one principle of Prometheus is that
target labels come from Prometheus and not exporters and consider what
would happen if two ELBs had the same name.

**Comment by migueleliasweb** [comment]
@lamont had a great point. I'm having the same issue now. The `role_arn` is global and not replicable per metric. I understand the concerns about the clash of names between accounts but this could be easily overcome by adding account_id to the final metric.
