### ISSUE TITLE
Unable to get console values on prometheus 

### ISSUE THREAD

**Issue by AashishChughHome** [prometheus/cloudwatch_exporter#127]
Hi I am getting rds cpu utilization as a graph form but when selecting console view it is showing no data points.

seems there should be an extra parameter.

![screenshot from 2018-07-31 13-57-41](https://user-images.githubusercontent.com/29576872/43447851-fff3760c-94c9-11e8-903c-cedb7ddc6da2.png)
![screenshot from 2018-07-31 13-57-58](https://user-images.githubusercontent.com/29576872/43447853-002d0052-94ca-11e8-8868-c38195ada476.png)

**Comment by brian-brazil** [comment]
This is expected, the data is 10m old which if you request data from now you won't see.

**Comment by AashishChughHome** [comment]
Yes my data is 10 m old as well as i am facing this issue for my another metrics like cpu_utilization.

And i am getting the memory data in bytes not in GB.
![screenshot from 2018-07-31 15-03-21](https://user-images.githubusercontent.com/29576872/43451673-1b07dc5e-94d3-11e8-863c-39c6d79a9e84.png)

**Comment by brian-brazil** [comment]
The units of data is a question for CloudWatch. You can always do match in PromQL to adjust them for display.

**Comment by AashishChughHome** [comment]
Thanks for the suggestion it is was really helpful for me.

Now i am trying to generate a alert in case of high cpu resolution like if cpu cross the 1 it will triggered a alert.

But it is not firing a alert if cpu cross 1.
![screenshot from 2018-08-03 13-29-21](https://user-images.githubusercontent.com/29576872/43631682-87776594-9721-11e8-9a26-1aad49424380.png)

**Comment by brian-brazil** [comment]
This is really a usage question. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
