### ISSUE TITLE
Cannot get AWS/RDS metrics with multiple Dimension

### ISSUE THREAD

**Issue by RedHat93** [prometheus/cloudwatch_exporter#129]
Hi all,

i'm using:
 - cloudwatchexporter-0.4
 - prometheus-2.3.2

I'm trying to pull the metrics from AWS/RDS in my Prometheous server using this config:

```
---
region: eu-west-1

# AWS RDS

- aws_namespace: AWS/RDS
  aws_metric_name: BinLogDiskUsage
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average, Maximum, Minimum]

- aws_namespace: AWS/RDS
  aws_metric_name: BurstBalance
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average, Maximum, Minimum]

- aws_namespace: AWS/RDS
  aws_metric_name: CPUUtilization
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average, Maximum, Minimum]

- aws_namespace: AWS/RDS
  aws_metric_name: CPUCreditUsage
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: CPUCreditBalance
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: DatabaseConnections
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average, Sum]
```

If i use this conf. file everything work perfectly.
I would like to have on my Prometheous a complete MAP of all the CW metrics with all Dimensions available, so i try to simply add the "EngineName" dimension in the metrics that support it, like: CPU utilization.

I update the CPUUtil entry in my conf file as follow:
```
- aws_namespace: AWS/RDS
  aws_metric_name: CPUUtilization
  aws_dimensions: [DBInstanceIdentifier, EngineName]
  aws_statistics: [Average, Maximum, Minimum]
```

After reloading the configuration the metrics stop collecting.
Can u please help me on how to achieve that?

I found the same issue also on EC2, trying to gather the Dimension "AutoScalingGroup".

Thx u so much in advance,

**RedHat93**

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
