### ISSUE TITLE
Create ability to specify a JAVA_OPTS environment variable

### ISSUE THREAD

**Issue by jimbeck** [prometheus/cloudwatch_exporter#131]
We would like to use the cloud watch exporter to read through an HTTP proxy. We can set this up via Java environment variables, unfortunately, the docker container does not allow for any further configuration of the JVM. Please allow users to specify an arbitrary `JAVA_OPTS` environment variable (`-Dhttp.proxyHost=my-proxy -Dhttp.proxyPort=80`) which will be passed on to `java`.

**Comment by brian-brazil** [comment]
If you need something custom, you are free to create your own variant of the docker container. We purposefully keep out of replicating the job of your own configuration management systems.

**Comment by frittentheke** [comment]
At least the JVM switches to auto-configure the heap sizes and GC should be set to efficiently deploy this on i.e. Kubernetes - see https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits

**Comment by brian-brazil** [comment]
Those are unrelated.

This is not something we're going to support directly, as it's a configuration management problem.
