### ISSUE TITLE
Reduce number of api operations by using GetMetricData API instead of GetMetricStatistics API

### ISSUE THREAD

**Issue by prasannamahajan** [prometheus/cloudwatch_exporter#134]
You can request 100 metrics using GetMetricData and 1 metric using GetMetricStatistics.

Pricing of GetMetricData and GetMetricStatistics is 
$0.01/1,000 metrics requested using GetMetricData
$0.01/1,000 GetMetricStatistics

So if you use GetMetricData, the overall cost would become 1% of current cost. (huge saving)

**Comment by brian-brazil** [comment]
That sounds promising, though I think it'd be less than that if you were requesting multiple statistics.

Would this also work for things like billing that only post stats once a day?

**Comment by prasannamahajan** [comment]
whatever woks with GetMetricStatistics will work with GetMetricData.
If you request multiple statistics of same metric in single GetMetricData then it would be counted as 1 request.

**Comment by ikben** [comment]
This may also allow people to use metric math (although this has probably impact on the configuration syntax), allowing for more useful data from cloudwatch:
Eg;
Getting (average) requests per seconds by dividing the per-minute metric by 60

**Comment by richardTowers** [comment]
Sadly the pricing of `GetMetricData` and `GetMetricStatistics` doesn't work like that - 

```
$0.01/1000 metrics requested using GetMetricData
...
$0.01/1,000 GetMetricStatistics ... requests
```

So although you can make 100 times fewer calls (requesting 100 metrics in each), the `GetMetricData` is billed _per metric_ whereas the `GetMetricStatistics` call is billed _per request_, so it doesn't actually change the cost. (I checked this interpretation of AWS' pricing model with AWS support).

The place where the pricing does differ is in the number of datapoints returned _for a single metric_ - `GetMetricData` supports far more datapoints, so if you can poll less often and request a lot of data in each poll then you can save costs that way. Sadly that adds latency that you probably don't want.

**Comment by brian-brazil** [comment]
Would using GetMetricData be an option for reducing the number of RPC calls and thus how long it takes to gather data?

**Comment by frioux** [comment]
I think it would reduce the number of calls and time, if I am understanding correctly.  I could try to implement a patch if you are interested

**Comment by brian-brazil** [comment]
Please go ahead. We'll only find out by trying it.

**Comment by frioux** [comment]
Because this code is relatively easy to write, we decided to build a new version in Go rather than work on the Java code.  It is notably faster due to GetMetricData usage.  You are welcome to either try to adopt the techniques or just fork the code and migrate it more to your style, or ignore it entirely :)

https://github.com/ZipRecruiter/monitoring--cloudwatch

**Comment by johannes-gehrs** [comment]
We have a prototype of this exporter which uses GetMetricData as opposed to GetMetricStatistics. Unfortunately you can NOT safe any cost using the API call (afawct).  Using GetMetricData you pay the same amount for 1,000 metrics that you pay for 1,000 GetMetricStatistics API calls. 

One metric is defined as a combination of metric name, dimension pairs and namespace. You can get multiple stats for one metric and it is only counted as one metric. Unfortunately, this is exactly  what you also get with GetMetricStatistics. The cost stays the same.

You can see this illustrated in the screenshot attached. We deployed the prototype mid day on the 10th of May. The solution was deployed 24h on the 11th and 12th. So the cost really stays the same. 

<img width="939" alt="Screenshot 2019-05-13 at 10 11 32" src="https://user-images.githubusercontent.com/2290644/57605799-c2b16e00-7567-11e9-8a50-2c2660e106fa.png">

The prototype is a lot quicker at retrieving the data from AWS, especially if you get a lot of dimensions. We could provide the source code if someone would be interested in polishing it to production level. For us this is not worthwhile as our main pain point is not performance but rather cost.

**Comment by johannes-gehrs** [comment]
We have a prototype of this exporter which uses GetMetricData as opposed to GetMetricStatistics. Unfortunately you can NOT safe any cost using the API call (afawct). Using GetMetricData you pay the same amount for 1,000 metrics that you pay for 1,000 GetMetricStatistics API calls.

One metric is defined as a combination of metric name, dimension pairs and namespace. You can get multiple stats for one metric and it is only counted as one metric. Unfortunately, this is exactly what you also get with GetMetricStatistics. The cost stays the same.

You can see this illustrated in the screenshot attached. We deployed the prototype mid day on the 10th of May. The solution was deployed 24h on the 11th and 12th. So the cost really stays the same.

<img width="939" alt="Screenshot 2019-05-13 at 10 11 32" src="https://user-images.githubusercontent.com/2290644/57608728-c8aa4d80-756d-11e9-8ef6-6c79da88d1cf.png">

The prototype is a lot quicker at retrieving the data from AWS, especially if you get a lot of dimensions. We could provide the source code if someone would be interested in polishing it to production level. For us this is not worthwhile as our main pain point is not performance but rather cost.

**Comment by johannes-gehrs** [comment]
I guess I should have read @richardTowers's comment more carefully which is 100% correct.

**Comment by brian-brazil** [comment]
Is it faster though?

**Comment by johannes-gehrs** [comment]
Yes, it is around 4 times faster and the implementation is not yet optimal because it makes at least one request per rule.

**Comment by brian-brazil** [comment]
That's still great, and likely more than fast enough in practice.

**Comment by johannes-gehrs** [comment]
It would be almost trivial to optimize the code in such a way that it makes only the minimum necessary amount of requests. Would you be willing to work on polishing it to production grade @brian-brazil? In that case I would provide the code.

**Comment by brian-brazil** [comment]
I'd be happy to take it as-is as a PR, an extra few call per rule is not the end of the world compared to how many we're saving per metric.

**Comment by johannes-gehrs** [comment]
Here's [my PR.](https://github.com/prometheus/cloudwatch_exporter/pull/186) Maybe someone is willing to step up and give it some love. I would not merge it as is. See my comments.

**Comment by deejvince** [comment]
There’s a recent feature that allows you to list metrics and filter by recently active. We can use it as a pre-call to decide which metrics to fetch, thus potentially reducing costs:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListMetrics.html

**Comment by brian-brazil** [comment]
I'm not sure that'd help in the general case, plus it could break for things like S3 that are only published once a day.

**Comment by mariana-mendes** [comment]
If you consider get more than one statistic, _get-metric-statistics_ should be cheaper, because _get-metric-data_ only supports a single statistic. Otherwise, the price stays the same. 

Considering 1000 instances: 
* get-metric-statistics:

| stats|  total requests	|  	cost|  
|-	|-	|-	|
| 3|  	1000 |$0,01|   	

* get-metric-data:

| stats|  total metrics/request|  	cost|  
|-	        |-	                                |-	       |
| 3 | 3000|  $0,03 |   	

I think several people have already explained it, so it's more like a doubt that I have. :sweat_smile:

**Comment by brian-brazil** [comment]
Yeah, it appears it's not cheaper but it is faster. If someone could get the PR above ready for review that'd be great.

**Comment by mghildiy** [comment]
I would fork @johannes-gehrs' MR and try to take it further.

**Comment by matthiasr** [comment]
(updated the issue title to reflect what you all found out about the pricing)

**Comment by jindalshivam09** [comment]
Hi all
Reviving this old thread and wondering if any progress has been made to use GetMetricData instead of GetMetricStatistics?

I found another solution [1] but it looks like this also uses GetMetricStatistics when dimensions are specified

[1] https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues

**Comment by matthiasr** [comment]
There has been no substantial progress but I am sure a lot of users would appreciate the faster scrape times.
Interesting that YACE switches method depending on the dimensions, is this a limitation of the GetMetricData API? Or an opportunity to make the dimensions automatic?

**Comment by or-shachar** [comment]
Hey everyone, feel free to have a first look at my purposed solution #414 . It still has few TODOs but I feel like this will allow to safely and carefully migrate to using getMetricData 

Would appreciate any comment
