### ISSUE TITLE
Pass `aws_dimension_select` filter values in `ListMetricsRequest`.

### ISSUE THREAD

**Issue by nishanth-pinnapareddy** [prometheus/cloudwatch_exporter#139]
Currently, we use `aws_dimension_select` values to filter out metrics after we list all the metrics with given dimensions. The scarpe becomes time consuming when there more metrics with a given dimension.. for example dynamodb `SuccessfulRequestLatency` metric with `TableName, Operation` as dimensions. There are around 6k metrics and scare takes around `5min`. But, Here we are intrested in getting metrics for a single table even if specify the table name in `aws_dimension_select` it stll takes same amount of time due to below reason.

In `getDimensions() (line 211)` function, while creating the `ListMetricsRequest` object we just add dimension Name but not the filter Value even if they are specified as part of `aws_dimension_select`. 
```
      for (String dimension: rule.awsDimensions) {
        dimensionFilters.add(new DimensionFilter().withName(dimension));
      }
```
and filter out it afterwards in `useMetric()` function. I don't what is the intention doing this way.

We can reduce the scrape time by passing the filter values in the scrape request itself. Something like below.
```
        for (String dimension: rule.awsDimensions) {
            if (rule.awsDimensionSelect != null && rule.awsDimensionSelect.get(dimension) != null) {
                List<String> filterValues = rule.awsDimensionSelect.get(dimension);
                for (String value : filterValues) {
                    dimensionFilters.add(new DimensionFilter().withName(dimension).withValue(value));
                }
            }
            else {
                dimensionFilters.add(new DimensionFilter().withName(dimension));
            }
        }
``` 
after the above changes my scrape took under a sec from 5 min. That's a drastic improvement.

If the maintainers feel this is a valid issue I can raise a PR with this changes.

**Comment by nishanth-pinnapareddy** [comment]
Yaa it doesn't support multiple values.

**Comment by brian-brazil** [comment]
That seems a bit much for users, the current idea is that a given metric is specified only once.

**Comment by nishanth-pinnapareddy** [comment]
yaa it's a trade-off between `efficiency vs simplicity` in this particular scenario. I would be happy to replicate metrics in config.yaml than waiting for 5 min.

**Comment by brian-brazil** [comment]
We could query the cross product of the values, though that could get expensive in some cases.

**Comment by steven-aerts** [comment]
I think my PR #143 covers this.

For multiple dimensions (not something I see a lot in the metrics provided by aws) I fall back to retrieving the list metrics from cloudwatch, as my guess is here that the number of permutations will explode.

Another optimization we can do is when someone specifies only one select value for a specific dimension, add it to the filter of the 'listMetrics' request.  But as I did not encounter these cases in the wild, I did not implement it.

**Comment by TarekAS** [comment]
Somewhat related, but it would be great if we can have an 'exclude' regex option that works the exact opposite of aws_dimension_select_regex. Using negative lookaheads is difficult and not clear.

**Comment by brian-brazil** [comment]
Unlike Go, Java regexes do support negative lookaheads so I don't see a need to add more options for something that's already possible.

**Comment by brian-brazil** [comment]
This was done.
