### ISSUE TITLE
Verbose logging on every CloudWatch API call

### ISSUE THREAD

**Issue by marians** [prometheus/cloudwatch_exporter#140]
Hey, we're grateful for cloudwatch_exporter and would like to have better visibility of what requests are fired to the AWS API, especially to monitor cost.

Would you be interested in a pull request that adds log output for every request made? I think this should go to log level `FINE`. Assuming that it would be too verbose for the standard case.

It would make sense to have the log level be configurable, e. g. via a command line flag. Is that already the case? If not, that could be part of the PR too.

**Comment by brian-brazil** [comment]
I'm okay with that, I'd expect the logging levels to come to the logging library from wherever it usually gets it (system properties or xml).

**Comment by marians** [comment]
@brian-brazil Thanks for the response!

I have the log lines addition here: https://github.com/giantswarm/cloudwatch_exporter/pull/1

There is a problem: I am unable to set a different log level for the server. I tried setting a custom `logging.properties` file via the `-Djava.util.logging.config.file` command line flag. properties content being `.level = FINE`. I also tried overwriting the main `logging.properties` file like this in the `Dockerfile`:

```Dockerfile
RUN echo ".level = FINE" > /etc/java-10-openjdk/logging.properties
```

All didn't help. The only log lines I see are

```
2018-10-11 12:45:39.241:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2018-10-11 12:45:39.341:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9106
```

Any idea how I could increase the log level at runtime?

**Comment by marians** [comment]
Hmm. I just changed the two log lines I wrote from `Level.FINE` to `Level.INFO`. I expected that to appear with the default log level, but it doesn't.

If you could point me to where to adjust the level, that would be appreciated. Thanks!

**Comment by brian-brazil** [comment]
I worked from https://www.robustperception.io/viewing-logs-for-the-jmx-exporter and it worked as expected.

**Comment by marians** [comment]
Thanks, that worked for me. However I won't pursue the PR.

**Comment by aledeganopix4d** [comment]
@marians I'm coming here with the same problem you originally had.
Unfortunately I see that your GitHub repo where you originally developed the PR has been deleted.
Any chance the code is still around? I also think this would be a very useful feature to have.
Thanks!

**Comment by marians** [comment]
The PR wasn't needed. Logging each request worked for me with the explanation given in https://www.robustperception.io/viewing-logs-for-the-jmx-exporter

**Comment by aledeganopix4d** [comment]
@marians I'm having some trouble figuring out the correct parameters to set in the properties file similarly to what's described in the blog post.
Also it might be a good idea to add this information to the project README.md, I can do that once I understand the good params (sorry I really know nothing about Java...).

**Comment by rayj-pgi** [comment]
I found this quite helpful.

logging.properties looks like this

```
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=ALL
io.prometheus.jmx.level=ALL
io.prometheus.jmx.shaded.io.prometheus.jmx.level=ALL
.level = FINE
```

run it like this

```
java -Djava.util.logging.config.file=logging.properties -jar cloudwatch_exporter-0.5.0-jar-with-dependencies.jar 9106 cloudwatch-exporter.yml
```
