### ISSUE TITLE
Have an option to specify aws-region at metric level

### ISSUE THREAD

**Issue by nishanth-pinnapareddy** [prometheus/cloudwatch_exporter#151]
I have my workloads running in us-west-2 region and AWS publishes trustedadvisor, billing metrics in us-east-1 region. So, I want cloudwatch_exporter to provide an option to specify region at metric level.
This can be achieved by following code changes: https://github.com/nishanth-pinnapareddy/cloudwatch_exporter/commit/a08f9166419a3ff828452e8429734c7d33092de8

```
        // If region is specified, set the corresponding endpoint
        if (rule.awsRegion != null) {
            Region region = RegionUtils.getRegion(rule.awsRegion);
            if (region != null) {
                config.client.setEndpoint(getMonitoringEndpoint(region));
            }
        }
```

@brian-brazil  I give a PR for this if it looks good

**Comment by brian-brazil** [comment]
The general idea is to run one cloudwatch exporter per region, cross-region api calls tend not to be very reliable.

**Comment by nishanth-pinnapareddy** [comment]
if the cross-region api fails, how does it affect the current application?  I see the worst thing that can happen is one of the cloudwatch requests fail.

**Comment by brian-brazil** [comment]
There'll be data missing, and cloudwatch is already generally scraped often.
