### ISSUE TITLE
Update to Java 11

### ISSUE THREAD

**Issue by swestcott** [prometheus/cloudwatch_exporter#156]
The `Dockerfile` currently uses OpenJDK 10. Oracle stopped shipping updates to this in September (https://www.oracle.com/technetwork/java/javase/java-se-support-roadmap.html). The docker build should switch to Java 11 to continue receiving updates.

Will follow-up with a PR.

**Comment by brian-brazil** [comment]
We're using OpenJDK, not Oracle Java.

**Comment by swestcott** [comment]
As I understand it (apologies it I've misunderstood), Oracle JDK and OpenJDK are build from the same source code, it's just the build tools that are different. OpenJDK is built using non-commercial build tools to allow it to shipped with Linux distros.

As Oracle has ceased support for Java 10 in September, I believe that means both the Oracle JDK and OpenJDK aren't getting fixes.

**Comment by brian-brazil** [comment]
Red Hat stepped up to do OpenJDK support.

**Comment by swestcott** [comment]
Yep, but only for LTS releases, so not 9 & 10.

https://access.redhat.com/articles/1299013
