### ISSUE TITLE
cloudwatch_exporter does not use ECS task role properly

### ISSUE THREAD

**Issue by tlwr** [prometheus/cloudwatch_exporter#164]
When running the `prom/cloudwatch-exporter` docker image on EC2 using ECS it is unable to get credentials from the ECS task role (i.e. via `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`) (see [this link](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/credentials.html))

The error message which appears in the logs is:
```
com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
```

Changing our ECS task definition to include the following hack:

```
"entryPoint": [
  "bash",
  "-c",
  "unset AWS_CONTAINER_CREDENTIALS_RELATIVE_URI",
  "unset AWS_EXECUTION_ENV",
  "java -jar /cloudwatch_exporter.jar 9106 /config/config.yaml"
]
```

forces the exporter to use the instance role instead of the task role, and if we give the instance role the same permissions as a task role then the exporter works as expected.

This is fine for our use-case because we are just using ECS to schedule the exporter as a daemon task on each EC2 node which runs prometheus, so using a task role is unnecessary.

I think this problem may be solved by using v2 of the SDK but I have not looked into the issue further.

@sakisv @matthewcullum-gds

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by brian-brazil** [comment]
Another one to go with #172 it sounds like.
