### ISSUE TITLE
post to reload doesn't work

### ISSUE THREAD

**Issue by itaysk** [prometheus/cloudwatch_exporter#169]
can't get HTTP POST to reload to work (in kubernetes)
repro:

`helm install stable/prometheus-cloudwatch-exporter`
`kubectl edit cm ${name-of-configmap}`
`curl -X POST http://${exporter-url}:9106/-/reload`
I see in the log:
```
io.prometheus.cloudwatch.CloudWatchCollector reloadConfig
INFO: Reloading configuration
```
but there's NO effect.
The configmap edit DID update the file in the container, as I can exec into the container and see the updated config under `/config/config.yml`.

If I `kubectl delete po ${pod-name}` it reloads with the updated config correctly.

**Comment by brian-brazil** [comment]
Is that a file bind mount?

**Comment by itaysk** [comment]
I guess so (uses kubernetes volume to mount), does that matter?

**Comment by brian-brazil** [comment]
Yes, it means the new file won't be visible as it's linked to an inode rather than a name. Mount the entire /config directory instead.

**Comment by itaysk** [comment]
sorry, I missed your emphasise on the *file* not on the bind mount. I think it's actually a directory: `mountPath: /config` https://github.com/helm/charts/blob/master/stable/prometheus-cloudwatch-exporter/templates/deployment.yaml#L89

**Comment by brian-brazil** [comment]
Can you reproduce this outside of a container environment?

**Comment by brian-brazil** [comment]
Haven't heard back, so I'll presume this was a local issue.

**Comment by BouchaaraAdil** [comment]
@brian-brazil this is still persisting, I have had to send a post request to reload API in order to take effect, otherwise, the config file just got updated after configmap changes in the container but is not taking effect.

**Comment by BouchaaraAdil** [comment]
@brian-brazil just saw [cloudwatch_exporter#reloading-configuration](https://github.com/prometheus/cloudwatch_exporter#reloading-configuration), is there any way to reload automatically without running manually `curl -x POST ...`

**Comment by matthiasr** [comment]
Automated reload on change is very complex, very prone to problems from partial files, and very operating-system dependent, so the exporter will not support it directly. In Kubernetes, you can run [configmap-reload](https://github.com/jimmidyson/configmap-reload) as a sidecar to trigger the reload.
