### ISSUE TITLE
Implement exponential back-off algorithm and bulking requests

### ISSUE THREAD

**Issue by gamunu** [prometheus/cloudwatch_exporter#170]
We have noticed that implementation if the `GetMetricStatistics` is not bulking the requests and doesn't implement exponential back-off algorithm. This is causing API requests to CloudWatch to be throttled.

The loop that is inefficient is in file:

https://github.com/prometheus/cloudwatch_exporter/blob/master/src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java, starting from line 345. GetMetricStatistics is called in line 348. there is no exception handling and we need to implement the exp. back-off and retry.

**Comment by brian-brazil** [comment]
There's no retries on purpose, if it fails it fails the whole scrape. As far as I'm aware there's no batch api.

**Comment by gamunu** [comment]
@brian-brazil thanks! I'll get back to this once I get a reply from AWS support team, let's see whether they can give us a better solution.

**Comment by brian-brazil** [comment]
Giving you more quota is the main thing that they can do.

**Comment by gamunu** [comment]
@brian-brazil you are correct. They increased the Quota 😄
