### ISSUE TITLE
Migrate to AWS version 2 Java API

### ISSUE THREAD

**Issue by silenceleaf** [prometheus/cloudwatch_exporter#172]
AWS version 2 api have already released for half year. Do you have plan to upgrade? It might be a refactoring.

**Comment by brian-brazil** [comment]
Are there benefits to the new API?

**Comment by Botono** [comment]
It fixes the crash reported in #182 which causes the exporter to stop.

**Comment by nsvijay04b1** [comment]
Any updates ?
