### ISSUE TITLE
Too many requests for a single metric?

### ISSUE THREAD

**Issue by gionn** [prometheus/cloudwatch_exporter#174]
Hi, new user here.

using the latest `prom/cloudwatch-exporter` docker image, I am evaluating this simple configuration to simply track egress bandwidth for each active instance (without the need of node-exporter that is a problem in my scenario):

```yaml
---
region: eu-west-1
period_seconds: 3600
metrics:
 - aws_namespace: AWS/EC2
   aws_metric_name: NetworkOut
   aws_dimensions: [InstanceId]
   aws_statistics: [Sum]
```

After manually invoking a few times the `/metrics` endpoint with curl I get:

```
# HELP aws_ec2_network_out_sum CloudWatch metric AWS/EC2 NetworkOut Dimensions: [InstanceId] Statistic: Sum Unit: Bytes
# TYPE aws_ec2_network_out_sum gauge
aws_ec2_network_out_sum{job="aws_ec2",instance="",instance_id="i-02cb617f2848431de",} 5871.0 1551949860000
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 10.662635096
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total{action="getMetricStatistics",namespace="AWS/EC2",} 505.0
cloudwatch_requests_total{action="listMetrics",namespace="AWS/EC2",} 5.0
```

I am surprised that the scrape duration takes more than 10 seconds, and that the `cloudwatch_requests_total{action="getMetricStatistics",namespace="AWS/EC2",}` metric is increasing of 101 calls each time I invoke the `/metrics` endpoint!

Is that an expected behaviour? I am quite frightened about the cloudwatch costs of that if using in 24h.

Thanks.

**Comment by brian-brazil** [comment]
I'm guessing you're a bit far away network wise, and the cost is not unexpected. If you just want to graph this I'd suggest using the Grafana Cloudwatch plugin, rather than pulling the data into Prometheus.

**Comment by gionn** [comment]
Thanks @brian-brazil for the reply.

In reality I am doing those tests from a decent broadband connection from Italy, latency is always below 50ms and a `aws ec2 describe-instances` finish in less than a second.

**Comment by brian-brazil** [comment]
That's all as expected then.

**Comment by gokhansengun** [comment]
How is 505 requests for a single instance expected?

Below metric indicates that there has been 5 runs

```
cloudwatch_requests_total{action="listMetrics",namespace="AWS/EC2",} 5.0
```

Output shows only one instance therefore we expect 5 `getMetricStatistics` instead of 505.

```
cloudwatch_requests_total{action="getMetricStatistics",namespace="AWS/EC2",} 505.0
```
