### ISSUE TITLE
Performace improvement with concurrent calls

### ISSUE THREAD

**Issue by gogineni99** [prometheus/cloudwatch_exporter#179]
Currently all the API call are done sequential and it takes minutes to retrieve the metrics. meshuga - https://github.com/meshuga/cloudwatch_exporter/tree/async_client has implemented concurrent processing so it takes very less time. However this is one year old. I have updated it to be in sync with latest - https://github.com/gogineni99/cloudwatch_exporter/tree/async_client

There is a huge improvement in the performance to populate prometheus endpoint.

Can this be merged to master branch ?

**Comment by brian-brazil** [comment]
This would break many many users, as Amazon throttles API calls a fair bit. It's also more polite to not hammer APIs. I'd suggest making sure your exporter is in the same region, and look if you need all the metrics.

**Comment by gogineni99** [comment]
Yaa I am using it on per region and only having metrics as needed. But as we start to use more AWS services the metrics we want to monitor also increases. The code also has an default of 50 concurrent calls and it can also be configured to a smaller value in yaml file.

**Comment by justinwatkinson** [comment]
Just wanted to pile on that I'm also in a similar boat.  For just two metrics for Application Load balancers, even in the scale of hundreds of load balancers, can cause the exporter to return data in well over a minute.  

With regards to the API, It looks like all of default limits for ListMetrics and GetMetricStatistics could potentially be increased for the customer.  Allowing the YAML option as suggested above seems like a fair trade-off.  I didn't look closely enough at the fork,,but could it also potentially emit a metric for how many times it got throttled as an early warning system?

**Comment by brian-brazil** [comment]
A throttled query will show up as a scrape failure.

**Comment by justinwatkinson** [comment]
I see, well that's good!

In any case, on top of the concurrency play, I believe there would also be a big benefit to moving over to the GetMetricData API endpoint as well (https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html).

It seems to be the way to get large amounts of data out of CloudWatch quickly.  Doing a quick look around, this appears to be the same API endpoint used by folks like Datadog for data extraction.

On a related performance subject, In my use case, the ListMetrics portion also takes about 1-2 seconds on average.  I think it'd be helpful to others as well, but caching that ListMetrics data for a configurable amount of time and dumping it on POST to /-/reload could help reduce metrics calls and greatly speed up things.

**Comment by brian-brazil** [comment]
#134 is tracking that.

**Comment by santijopo** [comment]
Hi all, just wanted to let everyone know that we're trying to get about 250 metrics with the forked branch listed above by @gogineni99 and we're getting Throttling errors from CW API. 

We can't seem to get the master branch cloudwatch-exporter up with that amount of metrics, since using sequential metric retrieval means going into a never ending wait with no result.

Should we be using another tool? or are expecting too much of this?

Thanks so much for the effort btw
