### ISSUE TITLE
"Illegal reflective access by com.amazonaws.util.XpathUtils" Error

### ISSUE THREAD

**Issue by Botono** [prometheus/cloudwatch_exporter#182]
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.amazonaws.util.XpathUtils (file:/cloudwatch_exporter.jar) to method com.sun.org.apache.xpath.internal.XPathContext.getDTMManager()
WARNING: Please consider reporting this to the maintainers of software.amazon.awssdk.core.util.XpathUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
These warnings are correlated with a gap in scraping. I am running the Exporter in AWS Fargate. The warnings occurred at 2019-04-26 01:43:00 UTC. All data from Exporter was missing from Prometheus from 2019-04-26 01:25:58 UTC until 2019-04-26 02:16:08 UTC. The Exporter container restarted during this time, after which everything returned to normal.

It looks like this warning has been fixed in v2 of the AWS API SDK: https://github.com/aws/aws-sdk-java-v2/issues/560

**Comment by brian-brazil** [comment]
We can track this under #172
