### ISSUE TITLE
A non-existent table "tables" shows in cloudwatch get-metric-statistics

### ISSUE THREAD

**Issue by marcindulak** [prometheus/cloudwatch_exporter#188]
First let me say this is **NOT** a `cloudwatch_exporter` problem, but I'm posting this as a question in parallel to https://forums.aws.amazon.com/thread.jspa?messageID=904078 for reference.

Sometimes I see a strange output from the cloudwatch get-metric-statistics. I can't see any throttling in the AWS web console for any of my tables or indexes. I'm sure I don't have a table called tables (I mean I've never seen this table and I'm not aware of any code creating it). All my tables are on-demand. Yet I obtain sometimes ThrottleEvents from the aws cloudwatch cli on a table called "tables". I know about those cases thanks to `cloudwatch_exporter`. Any idea what that `tables` table could be?

This is demonstrated below.

```
aws cloudwatch get-metric-statistics --namespace AWS/DynamoDB --metric-name WriteThrottleEvents --dimensions Name=TableName,Value=tables --start-time 2019-06-07T19:00:00Z --end-time 2019-06-07T21:00:00Z --period 3600 --statistics=Sum
```

```
{ "Label": "WriteThrottleEvents", "Datapoints": [ { "Timestamp": "2019-06-07T19:00:00Z", "Sum": 2.0, "Unit": "Count" } ] }
```

but this tables table does not exist, as shown by querying immediately

```
aws dynamodb describe-table --table-name tables
```

```
An error occurred (ResourceNotFoundException) when calling the DescribeTable operation: Requested resource not found: Table: tables not found
```

**Comment by brian-brazil** [comment]
I don't think there's anything for us to do here.
