### ISSUE TITLE
Need to close the FileReader?

### ISSUE THREAD

**Issue by rnzsgh** [prometheus/cloudwatch_exporter#189]
Greetings,

I have been digging around and I cannot determine that the FileReader is closed properly by the Yaml parser in the CloudWatchCollector. The Yaml object appears to wrap the Reader in the  org.yaml.snakeyaml.reader.StreamReader.java object which does not appear to close the Reader. If the FileReader is not closed properly this can result in a file descriptor and memory leak.

Ryan

**Comment by brian-brazil** [comment]
Would you like to send a PR? It's only opened once at startup, so leaking one FD isn't the end of the world.

**Comment by rnzsgh** [comment]
For sure :) PR submitted: https://github.com/prometheus/cloudwatch_exporter/pull/192
