### ISSUE TITLE
prometheus target status showing "up" but showing 'no data' in console

### ISSUE THREAD

**Issue by shivcena** [prometheus/cloudwatch_exporter#193]
> I am running prometheus in my linux server and while i am running it , the prometheus target status showing "up" but showing 'no data' in console

> I have ran "**promhttp_metric_handler_requests_total{code="200"}**" in the console, for this query it is showing "3" in metrics but getting "no data" in console.
![image](https://user-images.githubusercontent.com/52037533/60809647-c8fb4980-a1a8-11e9-8c85-8842e6c61ab2.png)
![image](https://user-images.githubusercontent.com/52037533/60809703-e6c8ae80-a1a8-11e9-98af-660344b01855.png)
![image](https://user-images.githubusercontent.com/52037533/60809753-0c55b800-a1a9-11e9-817b-88821fa542a2.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by shivcena** [comment]
![image](https://user-images.githubusercontent.com/52037533/60810303-728f0a80-a1aa-11e9-8c20-e36d950fb6c9.png)

**Comment by shivcena** [comment]
> Your reply make sense , but no body replying in prometheus-users mailing list :( :-(

**Comment by shivcena** [comment]
![image](https://user-images.githubusercontent.com/52037533/60812293-cb60a200-a1ae-11e9-97d4-852e0a5c5aa4.png)

**Comment by shivcena** [comment]
![image](https://user-images.githubusercontent.com/52037533/60812411-0ebb1080-a1af-11e9-9704-68ac9c8a88bb.png)

**Comment by george-angel** [comment]
If you check the logs on Prometheus you will see:

```
msg="Error on ingesting samples that are too old or are too far into the future"
```

Because of the timestamp on the metrics.

**Comment by palash2594** [comment]
@george-angel Can you please tell me how to check logs?
