### ISSUE TITLE
Join HTTP metrics in one metric

### ISSUE THREAD

**Issue by alexppg** [prometheus/cloudwatch_exporter#196]
Hi
First of all, thanks for all your work, this exporter is awesome!

What I'd like to propose is to make all the http metrics from one component, be part of the same metric instead of having multiple ones. The point of prometheus is to have one metric in which you can filter using labels, but this is not possible actually. For example, in the ELB metrics. If I want to query all the requests with return code of 2xx and 3xx, I'd have to do the next query:
```text
aws_elb_httpcode_backend_2_xx_sum AND aws_elb_httpcode_backend_3_xx_sum
```
This is not the prometheus way. The prometheus way would be:
```text
aws_elb_httpcode_backend{status=~"3xx|2xx"}
```
I think there should be at least an option to join metrics manually, but the best option would be that the ones that are known to be grouped, just group them and offer them to prometheus like they should be.

Also, I believe there shouldn't be hardcoded metrics with sum, average, etc, but that's another story.

Thanks

**Comment by brian-brazil** [comment]
If cloudwatch was to expose data that way (its data model allows for it) then that's what we'd do, however that's not how cloudwatch does it.

> Also, I believe there shouldn't be hardcoded metrics with sum, average, etc, but that's another story.

Also a Cloudwatch implementation choice. We're here to serve up what Cloudwatch provides, not try to second-guess or fix it.

**Comment by alexppg** [comment]
Sure, I know that cloudwatch exposes it this way. But would'nt be very valuable doing in the way I propose? Prometheus is big in instrumenting, this looks like an example use case for it.

**Comment by brian-brazil** [comment]
The Cloudwatch exporter is dumb, this is something to handle on AWS's end.

**Comment by alexppg** [comment]
I agree, but since we can't do that, adding this logic it in the exporter would be a nice workaround. I understand that you're not interested in changing the actual behavior, but would you accept PR to make this happen? Not that I would do it myself, but maybe another person would do it if the issue is tagged as `help-wanted` or something like that.

**Comment by brian-brazil** [comment]
No, I don't want to start having to maintain every potential fix to imperfect metrics from CloudWatch.

**Comment by alexppg** [comment]
Ok, I'll close then.
