### ISSUE TITLE
Support filtering by tags

### ISSUE THREAD

**Issue by discordianfish** [prometheus/cloudwatch_exporter#20]
The only way to filter metrics right now is by using aws_dimension_select(_regex), which requires the user to have control over the name of those dimensions and encode the necessary information in it to assign a cloudwatch_exporter.
I'd argue, it's common to have multiple stacks or environment in one AWS account which makes filtering by the existing dimensions cumbersome. More over, if CloudFormation is used, you can't even name some things like ElastiCache (or lose the possibility to update the cluster).

If the cloudwatch_exporter could use tags for filtering, a user can just provide a tag to define which metrics should be scraped by which exporter. Since the CloudWatch API itself doesn't support filtering by tags, the exporter would have to, depending on the metric source ("aws_namespace"). I'll use AWS/ELB as an example:

1) Get all ELBs in a region
2) Run describe-tags on the ELBs to find the one with the provided tag(s)
3) Use the ELB's name as a value for the LoadBalancerName dimension filter

**Comment by brian-brazil** [comment]
I'm not sure that it's sane to have this behaviour in the cloudwatch exporter, it requires adding special code for every single type of AWS resource and to maintain that over time.

This may be better done by generating an appropriate config on the user's part, as depending on how they're doing things there may be much more than just tags they want to filter on (e.g. VPC, security group).

**Comment by discordianfish** [comment]
@brian-brazil Yes, I understand that. I guess it depends on a trade off between UX and complexity. Then again, such option doesn't necessary need to work for every namespace. IMO would make sense to get some more feedback from AWS users.

**Comment by otm** [comment]
For me I would not like to filter on tags. But more the ability to add aws-tags as tags on the metrics. Especially on ELBs, as the name of the ELB when created with Cloudformation becomes very short.

**Comment by Luzifer** [comment]
For us having tags exported would be a huge improvement too. We're tagging resources according to teams and would like to build dashboards using those tags to group metrics for one team.

/cc @seiffert

**Comment by brian-brazil** [comment]
I think this is something you'd have to join on with a separate exporter, as we're kinda getting into what belongs as a target label territory.

**Comment by cconstantine** [comment]
This is something that would be very helpful for my team too.  What do you mean by `belongs as a target label territory`?

**Comment by ampedandwired** [comment]
I too would find this very useful as I'm struggling with how to implement functionality myself.

Relabel configs won't work, as the labels aren't exported to start with.  Writing out some `file_sd_configs` to apply labels won't work either, as they get applied to all metrics exported. So you would have to run a separate cloudwatch exporter for each AWS resource which is not reasonable.

The only solutions I can think of are to be to fork this exporter or decorate it with another exporter that adds the tags and re-exports (which seems inefficient).

Am I missing something obvious here?

**Comment by brian-brazil** [comment]
No, that's the effort involved. By my count there are currently 41 AWS services (and that's just AWS services) providing data in Cloudwatch. We're not going to add every possible object field from those.

This is the cloudwatch exporter, it pulls data from cloudwatch.

**Comment by ampedandwired** [comment]
No problem, I agree with your rationale for not wanting to include this in the cloudwatch exporter. Just making sure I understand the right approach. Shame that the CloudWatch API doesn't expose tags of the underlying resource somehow.

**Comment by tsupertramp** [comment]
Tried to build a cloudwatch exporter which has tag service discovery + tag as label metrics - https://github.com/ivx/yet-another-cloudwatch-exporter - cc: @brian-brazil - Thanks for your help during KubeCon!
