### ISSUE TITLE
Add config for EMR metrics

### ISSUE THREAD

**Issue by JogiInnov** [prometheus/cloudwatch_exporter#203]
Please add config for EMR metrics also in example.yml

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by JogiInnov** [comment]
Sure.

**Comment by hgaglani** [comment]
I am tad bit confused here. So are cloudwatch EMR metrics supported currently or not? and what would need changing to handle that?

**Comment by brian-brazil** [comment]
They're supported like any other Cloudwatch metric, our example config doesn't contain them though.
