### ISSUE TITLE
Auto detect AWS region

### ISSUE THREAD

**Issue by guidodobboletta** [prometheus/cloudwatch_exporter#207]
It would be nice to have this feature seeing as prometheus `ec2_sd_configs` allows this. It is ideal for people who want to build a universal AMI that would be run in different AWS accounts/regions without the need to have configuration overrides or hacky solutions.

**Comment by brian-brazil** [comment]
That code is in the aws library. If the same is in the Java one, you can send a PR.

**Comment by adjkilgore** [comment]
It would be useful to support AWS environment variables (e.g. AWS_REGION) that are available to the process, allowing this to be used in containers on Fargate.  It looks like the current implementation is EC2 specific because it relies on the EC2 metadata.
