### ISSUE TITLE
AWS/S3 metrics do not work

### ISSUE THREAD

**Issue by mrwacky42** [prometheus/cloudwatch_exporter#21]
With a barebones config file:
```
---
region: us-east-1
metrics:
- aws_namespace: AWS/S3
  aws_metric_name: BucketSizeBytes
```

I get no results. In fact, it doesn't even claim it's talking to AWS at all, and the request counter stays at zero.

```
curl -s 0:29992/metrics
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total 0.0
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 0.588527659
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
```

If I come back in 5 or ten seconds, `cloudwatch_requests_total` will increment by 1. But no errors, and no data.
I have fiddled about with various settings for dimensions, but never does it report any datas.

I can get this working fine for `AWS/ELB` resources, so I know I can talk to AWS.

**Comment by brian-brazil** [comment]
This is likely an issue on the AWS end. Can you get the data from the aws cli?

**Comment by mrwacky42** [comment]
I haven't tried CLI, but I can get data from the web console.
/me wanders off to try CLI

**Comment by mrwacky42** [comment]
Sure enough, it works if I try hard enough:

```
---
region: us-east-1
metrics:
- aws_namespace: AWS/S3
  aws_metric_name: BucketSizeBytes
  aws_dimensions: [BucketName, StorageType]
  aws_dimension_select:
    BucketName: [ mah-bucket ]
    StorageType: [StandardStorage]
  aws_statistics: [ Average ]
  period_seconds: 86400
  range_seconds: 604800
