### ISSUE TITLE
cloudwatch exporter not showing cloudwatch metrics

### ISSUE THREAD

**Issue by usernkey** [prometheus/cloudwatch_exporter#212]
I am running the latest cloudwatch exporter container

18f626c9d6d600882b6e521fc07b6ae084458045ec66f0bb93ac366e22d6151d

I have an AWS role

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "CloudwatchExporter",
            "Effect": "Allow",
            "Action": [
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:ListMetrics"
            ],
            "Resource": "*"
        }
    ]
}

I am providing the role to the pods using kube2iam and the config in a config map

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-exporter
  namespace: elk
  labels:
    app: cloud-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-exporter
  template:
    metadata:
      labels:
        app: cloud-exporter
      annotations:
        iam.amazonaws.com/role: "elk1-eu-west-2-dev-cloudwatchexporter"
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: cloud-exporter
            defaultMode: 0777
      containers:
        - name: cloud-exporter
          image: prom/cloudwatch-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9106
          livenessProbe:
            httpGet:
              path: /
              port: 9106
          readinessProbe:
            httpGet:
              path: /
              port: 9106
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 1500m
              memory: 10240Mi

---

apiVersion: v1
metadata:
  name: cloud-exporter
  namespace: elk
  labels:
    app: cloud-exporter
data:
  config.yml: |
    region: eu-west-2
    metrics:
      - aws_namespace: AWS/ES
        aws_dimensions: [DomainName]
        aws_metric_name: Nodes
        aws_statistics: [Average]
        aws_dimension_select:
          DomainName: [elk1-eu-west-2-dev]
        aws_statistics: [Average]

But when I check the metrics exported I get nothing even if the scrape seems successful 

root@cloud-exporter-7486dc46fd-89tcv:/# curl http://localhost:9106/metrics
cloudwatch_exporter_scrape_duration_seconds 0.04330818
cloudwatch_exporter_scrape_error 0.0
cloudwatch_requests_total{action="getMetricStatistics",namespace="AWS/ES",} 2.0

I can see this metric is there in cloudwatch 

aws cloudwatch list-metrics --profile dev

...
        {
            "Namespace": "AWS/ES",
            "Dimensions": [
                {
                    "Name": "DomainName",
                    "Value": "elk1-eu-west-2-dev"
                },
                {
                    "Name": "ClientId",
                    "Value": "902114603826"
                }
            ],
            "MetricName": "Nodes"
        },

....

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
