### ISSUE TITLE
Add optional timestamps to exposition data

### ISSUE THREAD

**Issue by otm** [prometheus/cloudwatch_exporter#22]
I made a quick hack which added timestamps to the exposition format (I hope I use the right term).  Like in the example below.

```
# HELP aws_elb_healthy_host_count_average CloudWatch metric AWS/ELB HealthyHostCount Dimensions: [LoadBalancerName] Statistic: Average Unit: Count
# TYPE aws_elb_healthy_host_count_average gauge
aws_elb_healthy_host_count_average{job="aws_elb",load_balancer_name="aaa",} 1.0 1455192180000
aws_elb_healthy_host_count_average{job="aws_elb",load_balancer_name="bbb",} 1.0 1455192180000
aws_elb_healthy_host_count_average{job="aws_elb",load_balancer_name="ccc",} 1.0 1455192180000
```

The advantage of this is that the timestamps in prometheus will match up with CloudWatch, which makes it easier if only a subset of data is exported and CloudWatch is needed for drilldown. Due to this I think this would be a really good option to be able to configure.

However, collector.MetricFamilySamples.Sample does not support the addition of timestamps, and write004 for instance does not either have support for this.

Would this be a desired feature, and in that case what would be the best way to implement it?

**Comment by brian-brazil** [comment]
As noted in the readme, this is pending https://github.com/prometheus/prometheus/issues/398

**Comment by jdub** [comment]
Is this now just waiting on a final Prometheus 2.0 release?

**Comment by brian-brazil** [comment]
No, that's not blocking this. The java client doesn't have timestamp support yet.

**Comment by zemek** [comment]
since https://github.com/prometheus/prometheus/issues/398 is closed, does that mean the exporter can support reading timestamps from cloudwatch?

**Comment by brian-brazil** [comment]
Not until I do a client_java release, which is on my todo list.

**Comment by Nyoroon** [comment]
Any updates?

**Comment by jdub** [comment]
Does #99 resolve this? The phrasing in the README is a little challenging to understand:

> CloudWatch has been observed to sometimes take minutes for reported values to converge. The default delay_seconds will result in data that is at least 10 minutes old being requested to mitigate this. The samples exposed will have the timestamps of the data from CloudWatch, so usual staleness semantics will not apply and values will persist for 5m for instant vectors.

Will existing samples be updated with new data from CloudWatch? If I reduce `delay_seconds`, can I bring Prometheus closer to to present (noting that there's a window of convergence)?

**Comment by brian-brazil** [comment]
It does, but releasing the change is still on my todo.

No, Prometheus is append-only. Yes.

**Comment by jdub** [comment]
@brian-brazil Great docs change, thanks!
