### ISSUE TITLE
Cloudwatch Exporter images not available in Quay org

### ISSUE THREAD

**Issue by aditya-konarde** [prometheus/cloudwatch_exporter#220]
Currently, the cloudwatch exporter images are pushed to Docker hub:
https://hub.docker.com/r/prom/cloudwatch-exporter 

I see that many other prometheus images are available in https://quay.io/organization/prometheus

RFE: We should try to maintain consistency by making the cloudwatch exporter images also available in the Prometheus organization in Quay. 

PS: I haven't checked yet, but this might be as simple as doing a `skopeo copy` in the post-build step to get started with

**Comment by brian-brazil** [comment]
Fixed by #299
