### ISSUE TITLE
exporter is not using AWS credentials from environment variables

### ISSUE THREAD

**Issue by funjon** [prometheus/cloudwatch_exporter#223]
Looks like the exporter is not picking up AWS credentials from environment variables. If I pass in a directory containing aws credentials to the docker container, the exporter succeeds in scraping CloudWatch stats; if I export those credentials as environment variables, I get nothing but errors. 

```
root@38a2248234e4:/# env | grep AWS
AWS_SECRET_ACCESS_KEY=4y5j[redacted]
AWS_ACCESS_KEY_ID=ASIA[redacted]
```

```
$ curl localhost:9106/metrics
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 0.1105924
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 1.0
```

**Comment by brian-brazil** [comment]
Are you sure they're in the environment of the exporter?

**Comment by funjon** [comment]
I'm running the docker container, so I should certainly hope so:

```
$ docker container ls
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
38a2248234e4        prom/cloudwatch-exporter   "java -jar /cloudwat…"   2 hours ago         Up 2 hours          0.0.0.0:9106->9106/tcp   flamboyant_minsky
$ docker container exec -it flamboyant_minsky bash
root@38a2248234e4:/# env | grep AWS
AWS_SECRET_ACCESS_KEY=4y5jl[snip]
AWS_ACCESS_KEY_ID=ASIA[snip]
```

**Comment by brian-brazil** [comment]
It's entirely the AWS library that's doing this handling, so I'd suspect the issue is on your end.

**Comment by funjon** [comment]
Then there's a bug in the AWS library; if I put those same credentials in a .aws/credentials file and make it available to the container, it is able to retrieve metrics successfully.

**Comment by surya74in** [comment]
my .aws/credentials has multiple account credential with different profiles. How can I pass this value in   cloudwatch-exporter

**Comment by Zeka13** [comment]
same problem here

**Comment by arvin495** [comment]
> 
> 
> my .aws/credentials has multiple account credential with different profiles. How can I pass this value in cloudwatch-exporter

If your cloudwatch-exporter server is on aws premises, you cloud use a role instead.

**Comment by dcepelik** [comment]
@funjon You may also need to provide `AWS_SESSION_TOKEN` in some cases (at least when yuo're using temporary credentials), could that be the case?

Anyway, working on my end just fine.

**Comment by brian-brazil** [comment]
Looks like the support requests here are resolved.
