### ISSUE TITLE
Outdated dependency in pom.xml

### ISSUE THREAD

**Issue by JavierZunzunegui** [prometheus/cloudwatch_exporter#23]
snakeyaml 1.17 appears to no longer be available, on 1.18 now.
https://oss.sonatype.org/content/repositories/snapshots/org/yaml/snakeyaml/

**Comment by brian-brazil** [comment]
Thanks for the report, we shouldn't be using SNAPSHOT versions at all. Would you like to send a PR?

**Comment by JavierZunzunegui** [comment]
Made PR https://github.com/prometheus/cloudwatch_exporter/pull/24 using non-SNAPSHOT snakeyaml.
