### ISSUE TITLE
Duplicate scrapes from cloudwatch exporter

### ISSUE THREAD

**Issue by alinoekialo** [prometheus/cloudwatch_exporter#235]
We are using cloudwatch exporter in production and are quite happy with it.

However, from time to time, we are seeing duplicate scrapes warning on our cluster and it looks like they originate from the cloudwatch exporter (according to prometheus log). The first time we've seen it, it was related to some AWS latency issue but it happened a couple of time since without related AWS issues. Any idea of a probable cause?

**Comment by brian-brazil** [comment]
> seeing duplicate scrapes warning

What exactly is this warning?

**Comment by alinoekialo** [comment]
The error log we are seeing from prometheus is:
```
level=warn ts=XXXX-XX-XXTXX:XX:XX.XXXZ caller=scrape.go:1191 component="scrape manager" scrape_pool=services/cloudwatch-exporter-prometheus-cloudwatch-exporter/0 target=http://XXX.XXX.XXX.XXX:9106/metrics msg="Error on ingesting samples with different value but same timestamp" num_dropped=1
```

**Comment by brian-brazil** [comment]
That indicates that convergence is taking quite a bit longer than expected inside CloudWatch, you could bump `delay_seconds` if you're seeing this regularly.

**Comment by alinoekialo** [comment]
Thank you very much we'll try that :)
