### ISSUE TITLE
Documentation for joining aws_resource_info with other metrics

### ISSUE THREAD

**Issue by dudicoco** [prometheus/cloudwatch_exporter#236]
I haven't been able to find documentation on how to filter metrics (for example aws_elb_request_count_sum) according to the aws_resource_info metric so that only the metrics matching the tags will be selected.
I'd appreciate if anyone could help with that and I suggest adding the information to the docs as well.

**Comment by schjan** [comment]
I used the documentation from a different project (https://github.com/ivx/yet-another-cloudwatch-exporter) to create the following query:

```
aws_elb_request_count_sum + on(load_balancer_name) group_left(tag_application, tag_environment) aws_resource_info
```

My ELBs are tagged with `application` and `environment`. I'm using [`group_left`](https://prometheus.io/docs/prometheus/latest/querying/operators/#many-to-one-and-one-to-many-vector-matches) to match the ELB stats with the tags from `aws_resource_info`.

You could also use this query to filter by Tags:
```promql
aws_elb_request_count_sum + on(load_balancer_name) group_left(tag_application, tag_environment) aws_resource_info{tag_environment="stage"}
```

**Comment by dudicoco** [comment]
Thanks @schjan!
I'm afraid I've already stopped using the cloudwatch_exporter due to the long delay in fetching the metrics from cloudwatch.
What is your use case for using the exporter?

**Comment by brian-brazil** [comment]
I don't think this exporter's docs are the place for general PromQL questions. There's already plenty of resources out there covering how to use info metrics.
