### ISSUE TITLE
Exporter will be broken if using aws_tag_select to specify the resources and there are ":" inside the label

### ISSUE THREAD

**Issue by ccjenniferhsu** [prometheus/cloudwatch_exporter#241]
When using `aws_tag_select` to select resources, it will generates `aws_resource_info` metrics with labels like `tag_$KeyName`. However, the exporter will be invalid for prometheus if  we select cloudformation based resource due to invalid label name.

Here is one example:

We used cloudformation to generate one RDS with stack name "grafanaRDS". According to [AWS resource tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html), it will have few tags got generated accordingly, and `aws:cloudformation:stack-name` is one of them. 

Next, I use `aws:cloudformation:stack-name` in the configuration:

>   - aws_namespace: AWS/RDS
        aws_metric_name: BinLogDiskUsage
        aws_dimensions: [DBInstanceIdentifier]
        aws_statistics: [Average]
        aws_tag_select:
          tag_selections:
            tag_aws:cloudformation:stack_name: ["grafanaRDS"]
          resource_type_selection: "rds:db"
          resource_id_dimension: DBInstanceIdentifier

From metrics page, it does generate the following metrics:
>aws_resource_info{job="aws_rds",instance="",arn="...",dbinstance_identifier="...",tag_Description="Grafana RDS",tag_aws:cloudformation:logical_id="DBGrafana",tag_aws:cloudformation:stack_id="...",tag_aws:cloudformation:stack_name="grafanaRds",} 1.0`

However, prometheus can't scrape this target correctly and is reporting `INVALID` error: 
![Screen Shot 2019-12-13 at 2 15 27 PM copy](https://user-images.githubusercontent.com/40581391/70956174-11584680-2028-11ea-95ac-7b65abc7962f.png)

The reason is the generated labels doesn't match [label regex](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) : `[a-zA-Z_][a-zA-Z0-9_]*` 

Since people might use cloudformation to generate AWS resource frequently, it would be nice if the exporter can support `aws_tag_select` feature with these. Could we fix this bug? Thanks!

**Comment by brian-brazil** [comment]
Would you like to send a PR to sanitize these?
