### ISSUE TITLE
Can I Use the one cloudwatch exporter.yml multi account ELB Metric Monitoring ?

### ISSUE THREAD

**Issue by jaehyukryu** [prometheus/cloudwatch_exporter#246]
Hello.
I Tried to Test for use the one yml for multi account monitoring like a below Ex. 
(All account was set cross account)
And I checked the localhost:9106/metrics, but can check the just one account data. If that is wrong,
 how can I resolve ?

Ex.)  
 - command 

java -jar target/cloudwatch_exporter-0.7.1-SNAPSHOT-jar-with-dependencies.jar 9106 test-cloudwatch.yml

- yml 

region: us-east-1
role_arn: arn:aws:iam::xxxxxxxxxxxxx:role/monitor
period_seconds: 300
range_seconds: 300
delay_seconds: 300
metrics:
 - aws_namespace: AWS/ELB
   aws_metric_name: UnHealthyHostCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [ELB-PRD-ABC-TEST]
   aws_statistics: [Maximum]
   period_seconds: 300
   range_seconds: 300

 - aws_namespace: AWS/ELB
   aws_metric_name: HealthyHostCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [ELB-PRD-ABC-TEST]
   aws_statistics: [Maximum]
   period_seconds: 300
   range_seconds: 300

region: us-east-1
role_arn: arn:aws:iam::zzzzzzzzzzzzz:role/monitor
period_seconds: 300
range_seconds: 300
delay_seconds: 300
metrics:
 - aws_namespace: AWS/ELB
   aws_metric_name: UnHealthyHostCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [ELB-PRD-ABC-TEST]
   aws_statistics: [Maximum]
   period_seconds: 300
   range_seconds: 300

 - aws_namespace: AWS/ELB
   aws_metric_name: HealthyHostCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [ELB-PRD-ABC-TEST]
   aws_statistics: [Maximum]
   period_seconds: 300
   range_seconds: 300

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
