### ISSUE TITLE
AWS metrics not showing anything for AWS/NATGateway namespace

### ISSUE THREAD

**Issue by jl98800** [prometheus/cloudwatch_exporter#252]
So I have a config file that looks something like this - to pull AWS/NATGateway metrics:

region: us-east-1
set_timestamp: false
metrics:
  - aws_namespace: AWS/NATGateway
    aws_metric_name: BytesInFromSource
    aws_dimensions: [Name, Value]
    aws_dimension_select:
        Name: [NatGatewayId]
        Value: [nat-0054ca2f0588e7ff0]
    aws_statistics: [Average]

The issue is - I'm not seeing aws_* type metrics - just CloudWatch exporter metadata metrics. 

# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 0.890600966
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
# HELP tagging_api_requests_total API requests made to the Resource Groups Tagging API
# TYPE tagging_api_requests_total counter
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total{action="getMetricStatistics",namespace="AWS/NATGateway",} 13701.0
cloudwatch_requests_total{action="listMetrics",namespace="AWS/NATGateway",} 109604.0

Everything seems to be configured correctly.  Has this been done before? Are there any examples out there to reference? 

I do know my AWS keys are configure, API calls are successful and the policy attached has full Get, List and Describe permission. I'm using the same user/keys/policy to pull cloudwatch metrics into Grafana successfully. 

I'm running cloudwatch_exporter in the docker image provided, deployed to a Kubernetes cluster and port forwarded for testing. Queries in prometheus show only cloudwatch_* metadata metrics. I was expecting to find aws_ prefixed metric parameters.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
