### ISSUE TITLE
Cannot connect via proxy

### ISSUE THREAD

**Issue by Stef3478** [prometheus/cloudwatch_exporter#26]
Hi, 

I'm trying to use this exporter but cannot connect via the proxy. I have set the environment variables http_proxy/https_proxy and supplied the proxy as arguments to java but it still doesn't work:

Mar 21, 2016 1:25:58 PM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: connect timed out
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
..
Mar 21, 2016 1:25:58 PM io.prometheus.cloudwatch.CloudWatchCollector collect
WARNING: CloudWatch scrape failed
com.amazonaws.AmazonClientException: Unable to execute HTTP request: connect timed out
..

Starting with:
$ java -Dhttp.useProxy=true -Dhttps.useProxy=true -Dhttps.proxyHost=http://proxy-dev.abc.com -Dhttps.proxyPort=3128 -Dhttp.proxyHost=http://proxy-dev.abc.com -Dhttp.proxyPort=3128 -jar ./target/cloudwatch_exporter-0.2-SNAPSHOT-jar-with-dependencies.jar 9106 config.yml

Surely I am not the only one using a proxy? How can I fix this?

Thanks
Stef

**Comment by brian-brazil** [comment]
We don't have any support for proxies, so if it's working it's going to be via the AWS libraries and java itself.

**Comment by Stef3478** [comment]
ok thanks.

**Comment by Tiduster** [comment]
For me it works perfectly.
Java doesn't like the "http://" at the start of your proxy address.

Try only with : **-Dhttps.proxyHost=proxy-dev.abc.com -Dhttps.proxyPort=3128 -Dhttp.proxyHost=proxy-dev.abc.com -Dhttp.proxyPort=3128**
No need for **useProxy=true** neither.

Regards,
