### ISSUE TITLE
AWS S3 Metrics to Prometheus not working

### ISSUE THREAD

**Issue by jachurra** [prometheus/cloudwatch_exporter#262]
Attached is my config.yaml file. Let me explain my environment. I am running Openshift Dedicated v 3.11 we have deployed Prometheus service and Prometheus exporter for AWS. The screenshot below shows that I am getting the RDS metrics but nothing for S3. I know S3 is only updated once a day but this has not updated for several days. Also I have already shutdown the Prometheus Pod and brought it back up and it just seems to be ignoring the S3 metrics. Any ideas or other questions you may have? Hope you can help
[config.zip](https://github.com/prometheus/cloudwatch_exporter/files/4376613/config.zip)
![Prometheus-AWS](https://user-images.githubusercontent.com/42154456/77454518-03585580-6dcf-11ea-9403-a0f04f0ab8a0.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by jachurra** [comment]
Okay, I will send it out via the email link you sent and see what happens

 

Thank you

 

Juan Achurra, Certified AWS SysOps Administrator, MS M.I.S.

Enterprise Service Management 

561-990-8335

 

Verify Certifications:

 

 <https://www.certmetrics.com/amazon/public/badge.aspx?i=3&t=c&d=2018-07-27&ci=AWS00572278>  <https://verify.accredible.com/input?type=id&value=13774102&custom=false&_ga=2.2682800.1247400725.1568927206-84574531.1568927206>

**Comment by jachurra** [comment]
Hi Brian, Im getting a little worried no one is responding to my post on the mailing list
