### ISSUE TITLE
Upgrade AWS SDK to version 2

### ISSUE THREAD

**Issue by willejs** [prometheus/cloudwatch_exporter#269]
Currently this exporter uses the 1.11 Java AWS SDK that [renews credentials if they expire within 15 minutes](https://github.com/aws/aws-sdk-java/issues/1893#issuecomment-606861234). This generally is not a common pattern within SDKs as noted in the issue above. This causes issues when running the exporter with KIAM out of the box. Specifically it repeatedly hammers the KIAM agent in an attempt to renew the credentials, as it thinks they are out of date. I have seen this firsthand in IAM prom metrics and via tcpdump. I think upgrading to 2.x will use a sensible 5m refresh window, although not confirmed.

**Comment by brian-brazil** [comment]
Feel free to send a PR.

**Comment by willejs** [comment]
Sorry, i hope this didn't seem like I was directing this at yourself @brian-brazil . I was really hoping to highlight this as a potential issue and make others aware of this. When you search for 'kiam' on the issues of the project, nothing is shown, i think [this issue](is related though). Glad to know that pull requests are welcome. I will take a look tomorrow.

**Comment by willejs** [comment]
Thanks @brian-brazil
