### ISSUE TITLE
MediaConvert metrics not reflected correctly

### ISSUE THREAD

**Issue by nosteine** [prometheus/cloudwatch_exporter#277]
Hi

I have a MediaConvert queue that I am monitoring using cloudwatch_exporter.
Here is the config:
```
- aws_namespace: AWS/MediaConvert
  aws_metric_name: JobsCompletedCount
  aws_dimensions: [Queue]
  aws_statistics: [SampleCount,Sum]
  set_timestamp: false
```
However, the **Sum** does not match what I am seeing when looking at the same metric on cloudwatch.
__For example a the same point in time__:
In AWS:
![image](https://user-images.githubusercontent.com/24456544/83347293-ec813280-a32c-11ea-9777-23c962c90c91.png)

**This is the cloudwatch source for the graph:**
```
{
    "metrics": [
        [ "AWS/MediaConvert", "JobsCompletedCount", "Queue", "arn:aws:mediaconvert:eu-west-1:155583592397:queues/Default" ]
    ],
    "view": "singleValue",
    "stacked": false,
    "region": "eu-west-1",
    "stat": "Sum",
    "period": 3600
}
```
However, cloudwatch_exporter insists that SUM is 2:
`aws_mediaconvert_jobs_completed_count_sample_count{job="aws_mediaconvert",instance="",queue="arn:aws:mediaconvert:eu-west-1:155583592397:queues/Default",} 2.0`

Can someone please help me understand why am I seeing this difference?

**Comment by brian-brazil** [comment]
One is a Count, the other a Sum. These are different metrics.

**Comment by nosteine** [comment]
@brian-brazil, I pasted the wrong metric from Prometheus. This is the Sum metric:
`aws_mediaconvert_jobs_completed_count_sum{job="aws_mediaconvert",instance="",queue="arn:aws:mediaconvert:eu-west-1:155583592397:queues/Default",} 2.0`
Still 2

**Comment by brian-brazil** [comment]
You're probably looking at a different timeframe or something. This exporter only takes the raw data that cloudwatch provides, no math is performed.

**Comment by nosteine** [comment]
ok, so trying to understand here.
What I need (to aggregate into Prometheus) is the current value of the gauge that describes the number of MediaConvert jobs completed.
Then I can use PromQL functions like **sum** or **increase** to calculate for example the **how many jobs completed in the last hour**

Which metric should I be scraping from cloudwatch then ?

**Comment by brian-brazil** [comment]
That's a MediaConvert question, this exporter blindly proxies the numbers from cloudwatch so I'm afraid I can't help you there.

**Comment by nosteine** [comment]
@brian-brazil, after creating an AWS support ticket for this, I think what I actually need is the total count of the MediaConvert jobs at this point of time. 
I believe that cloudwatch does not give me this. It already treats the metrics as graphs and not as counters.
Let me explain. It seems that by default, when asking for **sum** I am actually getting the **sum in the last 5 minutes**. In order to change that, then I have to manually change graph query to **1h** or **1d**.
What i don't get, is the actual and total number of jobs since cloudwatch started counting them so i can't present a **increase in the last hour** graph in Prometheus because the metrics I am getting are already relative and not absolute ...
I am not sure how to continue here ...

**Comment by brian-brazil** [comment]
All cloudwatch metrics are gauges, not counters. This seems like a usage question so 
 it'd make more sense to ask it on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by nosteine** [comment]
Thanks
