### ISSUE TITLE
Cloudwatch exporter is not caching AWS credentials

### ISSUE THREAD

**Issue by gwkunze** [prometheus/cloudwatch_exporter#280]
We are running the cloudwatch_exporter in Kubernetes using [Kiam](https://github.com/uswitch/kiam) to provide it with an instance profile. We're seeing over a thousand requests to our kiam server from the exporter every minute. It should be caching the information. I'm guessing this is caused by re-creating a credential provider every time instead of re-using it.

**Comment by brian-brazil** [comment]
As far as I can see from the code we only do credential stuff once per config load.

**Comment by gwkunze** [comment]
The code seems to be cloning the client every `collect` so I'm guessing any cache gets discarded every time

**Comment by brian-brazil** [comment]
Would you like to send a PR to fix that?

**Comment by gwkunze** [comment]
I dove into it a bit, it wasn't the clone thing (clone does a shallow copy by default anyways). The problem is by default the Java AWS SDK refreshes credentials once they're within 15 minutes of expiring, and KIAM by default issues credentials which last 15 minutes, which in effect causes it to refresh the credentials for every AWS API call.

Running test with a reconfigured Kiam instance, I suspect this will fix our issue

**Comment by brian-brazil** [comment]
So the exporter isn't doing anything wrong then?

**Comment by gwkunze** [comment]
The test seems to indicate that this fixes the issue, yes, the problem was not with the exporter. Apologies!

**Comment by jujugrrr** [comment]
Hi @gwkunze  / @brian-brazil We are hitting the same issue here but we use AWS EKS + Service role mapping rather than KIAM. The process is a bit different as it uses K8S OIDC to get credentials. I couldn't find any way to increase this session token duration. Would you have any clue?

Thanks a lot
