### ISSUE TITLE
Specify how often to make requests to CloudWatch

### ISSUE THREAD

**Issue by anthonyt123** [prometheus/cloudwatch_exporter#281]
I was wondering if there is anyway to set how frequently requests are made to CloudWatch? 

At the moment, I only need data for one SQS queue and ideally I'd like to fetch that data every minute but at the moment, according to the cloudwatch_requests_total metric, the exporter is making a request to CloudWatch every second when I'd rather check this queue every minute for my use case and to keep costs down

**Comment by brian-brazil** [comment]
Requests are only made when the exporter is scraped, so it sounds like something else is also hitting the exporter.
