### ISSUE TITLE
Specify port as part of the configuration file

### ISSUE THREAD

**Issue by dkrutsko** [prometheus/cloudwatch_exporter#284]
We are deploying `cloudwatch_exporter` across multiple regions and according to [this](https://github.com/prometheus/cloudwatch_exporter/issues/151#issuecomment-435143902), we have to run one instance per region. Ideally, we would like to run these all on one server and use a templated systemd service file to define them.

Everything is working fine except we need to specify the port and there doesn't appear to be a simple way to pass it as part of the template parameters (i.e. `cloudwatch-exporter@us-east-1`). It would be very helpful if the port parameter was just configurable through the configuration file so we can define the port per region.

Example templated systemd service file illustrating the problem

```
[Unit]
Description=CloudWatch Exporter for %I
Documentation=https://github.com/prometheus/cloudwatch_exporter
After=network-online.target syslog.target local-fs.target
Wants=network-online.target

[Service]
Type=simple
Group=cloudwatch-exporter
User=cloudwatch-exporter
ExecStart=/usr/bin/java -jar /usr/local/bin/cloudwatch.jar 9106 /etc/cloudwatch-exporter/cloudwatch/%i.yml
ExecReload=/usr/bin/curl -X POST http://localhost:9106/-/reload
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
```

**Comment by brian-brazil** [comment]
Like all other exporters in the Prometheus org, the port number comes from the command line and we try to have a given piece of configuration only come from one place for the sake of sanity. Accordingly this is something you'll have to handle via configuration management if you need to vary it.
