### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of com.fasterxml.jackson.core:jackson-core:jar

### ISSUE THREAD

**Issue by Bing-ok** [prometheus/cloudwatch_exporter#286]
Hi, there are multiple versions of <b><i>com.fasterxml.jackson.core:jackson-core</i></b> in <b><i>cloudwatch_exporter-master</i></b>. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only <b><i>com.fasterxml.jackson.core:jackson-core:2.10.0.pr1</i></b> can be loaded, and <b><i>com.fasterxml.jackson.core:jackson-core:2.6.7</i></b> will be shadowed.

As <b><i>com.fasterxml.jackson.core:jackson-core:2.6.7</i></b> has not been loaded during the building process, several methods are missing. However, the missing methods:
<b><i>1. com.fasterxml.jackson.core.base.GeneratorBase: com.fasterxml.jackson.core.json.JsonWriteContext getOutputContext()</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;io.prometheus.cloudwatch.CloudWatchCollector: void loadConfig(java.io.Reader,com.amazonaws.services.cloudwatch.AmazonCloudWatch,com.amazonaws.services.resourcegroupstaggingapi.AWSResourceGroupsTaggingAPI)&gt; D:\githubProject\cloudwatch_exporter-master\target\classes
</br>&lt;io.prometheus.cloudwatch.CloudWatchCollector: void loadConfig(java.util.Map,com.amazonaws.services.cloudwatch.AmazonCloudWatch,com.amazonaws.services.resourcegroupstaggingapi.AWSResourceGroupsTaggingAPI)&gt; D:\githubProject\cloudwatch_exporter-master\target\classes
</br>&lt;com.amazonaws.client.builder.AwsClientBuilder: void setRegion(java.lang.String)&gt; D:\Maven\Repositories\com\amazonaws\aws-java-sdk-core\1.11.708\aws-java-sdk-core-1.11.708.jar
</br>&lt;com.amazonaws.client.builder.AwsClientBuilder: com.amazonaws.client.builder.AwsClientBuilder withRegion(java.lang.String)&gt; D:\Maven\Repositories\com\amazonaws\aws-java-sdk-core\1.11.708\aws-java-sdk-core-1.11.708.jar
</br>&lt;com.amazonaws.client.builder.AwsClientBuilder: com.amazonaws.regions.Region getRegionObject(java.lang.String)&gt; D:\Maven\Repositories\com\amazonaws\aws-java-sdk-core\1.11.708\aws-java-sdk-core-1.11.708.jar
</br>&lt;com.amazonaws.regions.RegionUtils: com.amazonaws.regions.Region getRegion(java.lang.String)&gt; D:\Maven\Repositories\com\amazonaws\aws-java-sdk-core\1.11.708\aws-java-sdk-core-1.11.708.jar
</br>&lt;com.amazonaws.regions.RegionUtils: com.amazonaws.regions.RegionMetadata getRegionMetadata()&gt; D:\Maven\Repositories\com\amazonaws\aws-java-sdk-core\1.11.708\aws-java-sdk-core-1.11.708.jar
</br>&lt;com.amazonaws.regions.RegionUtils: void initialize()> D:\Maven\Repositories\com\amazonaws\aws-java-sdk-core\1.11.708\aws-java-sdk-core-1.11.708.jar
</br>&lt;com.amazonaws.regions.RegionMetadataFactory: com.amazonaws.regions.RegionMetadata create()&gt; D:\Maven\Repositories\com\amazonaws\aws-java-sdk-core\1.11.708\aws-java-sdk-core-1.11.708.jar
</br>&lt;com.amazonaws.partitions.PartitionsLoader: com.amazonaws.partitions.PartitionMetadataProvider build()&gt; D:\Maven\Repositories\com\amazonaws\aws-java-sdk-core\1.11.708\aws-java-sdk-core-1.11.708.jar
</br>&lt;com.amazonaws.partitions.PartitionsLoader: com.amazonaws.partitions.model.Partitions loadPartitionFromStream(java.io.InputStream,java.lang.String)&gt; D:\Maven\Repositories\com\amazonaws\aws-java-sdk-core\1.11.708\aws-java-sdk-core-1.11.708.jar
</br>&lt;com.amazonaws.util.IOUtils: void closeQuietly(java.io.Closeable,org.apache.commons.logging.Log)&gt; D:\Maven\Repositories\com\amazonaws\aws-java-sdk-core\1.11.708\aws-java-sdk-core-1.11.708.jar
</br>&lt;com.fasterxml.jackson.dataformat.cbor.CBORGenerator: void close()&gt; D:\Maven\Repositories\com\fasterxml\jackson\dataformat\jackson-dataformat-cbor\2.6.7\jackson-dataformat-cbor-2.6.7.jar
</br>&lt;com.fasterxml.jackson.core.base.GeneratorBase: com.fasterxml.jackson.core.json.JsonWriteContext getOutputContext()&gt;
</details>

The above missing methods are actually referenced by <b><i>cloudwatch_exporter-master</i></b>, which will cause “NoSuchMethodErrors” at runtime.

Suggested fixing solutions:
1. Declare direct dependency <b><i>com.fasterxml.jackson.core:jackson-core</i></b> to <b><i>2.6.7</i></b>
2. Use <&lt;exclude&gt; to exclude <b><i>com.fasterxml.jackson.core:jackson-core:2.10.0.pr1</i></b> from the dependency tree
3. Use configuration attribute &lt;dependencyManagement&gt; to unify the version of library <b><i>com.fasterxml.jackson.core:jackson-core</i></b> to be <b><i>2.6.7</i></b> in cloudwatch_exporter-master's pom file.

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

Dependency tree----
<details>
<summary>click for details</summary>
</br>[INFO] io.prometheus.cloudwatch:cloudwatch_exporter:jar:0.8.1-SNAPSHOT
</br>[INFO] +- com.amazonaws:aws-java-sdk-cloudwatch:jar:1.11.708:compile
</br>[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.708:compile
</br>[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
</br>[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.9:compile
</br>[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
</br>[INFO] |  |  |  +- (commons-logging:commons-logging:jar:1.2:compile - omitted for conflict with 1.1.3)
</br>[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.11:compile
</br>[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
</br>[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.6.7.3:compile - omitted for conflict with 2.10.0.pr1)
</br>[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7:compile
</br>[INFO] |  |  |  \- <b>(com.fasterxml.jackson.core:jackson-core:jar:2.6.7:compile - omitted for duplicate)</b>
</br>[INFO] |  |  \- joda-time:joda-time:jar:2.8.1:compile
</br>[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.708:compile
</br>[INFO] |     \- (com.fasterxml.jackson.core:jackson-databind:jar:2.6.7.3:compile - omitted for duplicate)
</br>[INFO] +- com.amazonaws:aws-java-sdk-sts:jar:1.11.708:compile
</br>[INFO] |  +- (com.amazonaws:aws-java-sdk-core:jar:1.11.708:compile - omitted for duplicate)
</br>[INFO] |  \- (com.amazonaws:jmespath-java:jar:1.11.708:compile - omitted for duplicate)
</br>[INFO] +- com.amazonaws:aws-java-sdk-resourcegroupstaggingapi:jar:1.11.708:compile
</br>[INFO] |  +- (com.amazonaws:aws-java-sdk-core:jar:1.11.708:compile - omitted for duplicate)
</br>[INFO] |  \- (com.amazonaws:jmespath-java:jar:1.11.708:compile - omitted for duplicate)
</br>[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.0.pr1:compile
</br>[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0.pr1:compile
</br>[INFO] |  \- <b>com.fasterxml.jackson.core:jackson-core:jar:2.10.0.pr1:compile</b>
</br>[INFO] +- org.yaml:snakeyaml:jar:1.17:compile
</br>[INFO] +- io.prometheus:simpleclient:jar:0.7.0:compile
</br>[INFO] +- io.prometheus:simpleclient_servlet:jar:0.7.0:compile
</br>[INFO] |  +- (io.prometheus:simpleclient:jar:0.7.0:compile - omitted for duplicate)
</br>[INFO] |  \- io.prometheus:simpleclient_common:jar:0.7.0:compile
</br>[INFO] |     \- (io.prometheus:simpleclient:jar:0.7.0:compile - omitted for duplicate)
</br>[INFO] +- org.eclipse.jetty:jetty-servlet:jar:9.4.15.v20190215:compile
</br>[INFO] |  \- org.eclipse.jetty:jetty-security:jar:9.4.15.v20190215:compile
</br>[INFO] |     \- org.eclipse.jetty:jetty-server:jar:9.4.15.v20190215:compile
</br>[INFO] |        +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
</br>[INFO] |        +- org.eclipse.jetty:jetty-http:jar:9.4.15.v20190215:compile
</br>[INFO] |        |  +- org.eclipse.jetty:jetty-util:jar:9.4.15.v20190215:compile
</br>[INFO] |        |  \- (org.eclipse.jetty:jetty-io:jar:9.4.15.v20190215:compile - omitted for duplicate)
</br>[INFO] |        \- org.eclipse.jetty:jetty-io:jar:9.4.15.v20190215:compile
</br>[INFO] |           \- (org.eclipse.jetty:jetty-util:jar:9.4.15.v20190215:compile - omitted for duplicate)
</br>[INFO] +- junit:junit:jar:4.11:test
</br>[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
</br>[INFO] \- org.mockito:mockito-all:jar:1.8.4:test
</details>

**Comment by brian-brazil** [comment]
> Please let me know which solution do you prefer? I can submit a PR to fix it.

My understanding is that the one AWS uses has security issues, but they can't upgrade for backwards compatibility reasons. Thus we force a newer version.

I'm not sure what to do here offhand, as we have had users ask that we not use the version that AWS requires.

**Comment by Bing-ok** [comment]
I see that the project has migrated AWS SDK to v2 from [PR-303,](https://github.com/prometheus/cloudwatch_exporter/pull/307) , so jackson-core version conflict is resolved. Thanks for your support!
