### ISSUE TITLE
AWS/EC2/API Namespace Metrics Not Working

### ISSUE THREAD

**Issue by midnightconman** [prometheus/cloudwatch_exporter#289]
I have tried versions 0.6.0 and 0.8.0 and I haven't been able to get the `AWS/EC2/API` namespace working correctly. I am able to scrape metrics from other namespaces, so I know in general my configurations are working, I have tried the following:
- setting the `delay_seconds` setting from 300-900
- setting the `range_seconds` setting from 300-900
- setting the `period_seconds` setting from 60-300
- leaving the `aws_dimensions` setting as default and specifying it

I am using the following configuration:
```
"metrics":
  "aws_dimensions":
  - "Per-Action Metrics"
  "aws_metric_name": "SuccessfulCalls"
  "aws_namespace": "AWS/EC2/API"
  "aws_statistics":
  - "SampleCount"
  "delay_seconds": 900
  "period_seconds": 300
"region": "us-west-2"
```

I get something like the following when I hit the metrics endpoint and I don't get any info in the logs:
```
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 0.08225348
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total{action="listMetrics",namespace="AWS/EC2/API",} 16.0
```

**Comment by brian-brazil** [comment]
Do you have a awscli command that provides the data you want? Once you have that, provide the same settings to the exporter.

**Comment by midnightconman** [comment]
Thank you, that got me down the path to discover it was an issue with my AWS SDK key permissions. Sorry for the trouble, it's working now.
