### ISSUE TITLE
Scrape duration

### ISSUE THREAD

**Issue by Stef3478** [prometheus/cloudwatch_exporter#29]
Hi,

I've got an issue with scraping for Network metric of the Instances. A scrape takes a very long time, 18 seconds or more. Scraping other metrics, like cpu utilization or scraping the same metric but for an AutoScalingGroupName works fine.
Also I cannot get metrics for an individual instance, as if the select filter doesn't work. It only gives me all instances, even if the select filter is applied for an individual instance.

I've attached a file with the configuration of the scraper and the output.

Any ideas?
Thanks
Stef

[scraping.txt](https://github.com/prometheus/cloudwatch_exporter/files/202359/scraping.txt)

**Comment by brian-brazil** [comment]
You've a typo, dimension should be singular in `aws_dimension_select`,

For things like network stats I'd recommend using the node exporter if you can, as that'll give you much better information for cheaper.

**Comment by Stef3478** [comment]
Yes indeed! This fixed both my issues;-)!
Thanks!
