### ISSUE TITLE
Repeating ALB data points

### ISSUE THREAD

**Issue by TheComice** [prometheus/cloudwatch_exporter#291]
Hi all, I am getting some odd looking ALB gauge data points which don't appear to correlate with the metrics in AWS Cloudwatch Console. Confirmed by testing different delay_seconds , scrape_intervals scrape config settings on a small number of metrics and resources. Please see example CWE config below: -

`---
region: eu-west-2
set_timestamp: true

metrics:
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_2XX_Count
  aws_dimensions: [LoadBalancer]
  aws_dimension_select:
    LoadBalancer: [alb name]
  aws_statistics: [Sum]`

with Prometheus scrape config as seen below: -

`
- job_name: cloudwatch
  scrape_timeout: 30s
  scrape_interval: 1m
  metrics_path: /metrics
  scheme: http
  dns_sd_configs:
  - names:
    - monitor-cw-alb.<%= ENV['DOMAIN'] %>
`

The raw samples can be seen below. 

`
aws_applicationelb_httpcode_target_2_xx_count_sum{exported_job="aws_applicationelb",instance="<sd_hostname>:32778",job="cloudwatch",load_balancer="<alb_name>"}	10 @1595353087.942
10 @1595353133.851
1 @1595353193.851
1 @1595353253.851
1 @1595353313.851
1 @1595353373.851
1 @1595353433.851
1 @1595353493.851
1 @1595353553.851
1 @1595353613.851
1 @1595353673.851
1 @1595353733.851
`

When looking at cloudwatch console for the same period I have only: -
`{
    "Datapoints": [
        {
            "Timestamp": "2020-07-21T17:27:00Z", 
            "Sum": 10.0, 
            "Unit": "Count"
        }, 
        {
            "Timestamp": "2020-07-21T17:28:00Z", 
            "Sum": 1.0, 
            "Unit": "Count"
        }
    ], 
    "Label": "HTTPCode_Target_2XX_Count"
}`

Any assistance would be welcome?

**Comment by TheComice** [comment]
Just to add I've got Prometheus setup with Thanos in a HA setup with two container instance running but just one CloudWatch Exporter. Could this be something to do with deduplication failing? But then why so many "1.0"s returned.

**Comment by brian-brazil** [comment]
Those data points are for different time periods, I see nothing wrong here. The cloudwatch exporter only returns what it gets from cloudwatch.

**Comment by TheComice** [comment]
Thanks for replying Brian. I can't understand why they would have different timeperiods set since the CloudWatch API calls show the "1.0" should have one timestamp of "2020-07-21T17:28:00Z". Am i using the set_timestamp boolean incorrectly?

**Comment by brian-brazil** [comment]
The console data is from around 10 minutes before the exporter data, they're for different times.

**Comment by TheComice** [comment]
Yes I see that, so if I've got two instances of Prometheus running with the one cloudwatch exporter. Could my instances be capturing the data with two timestamps and then thanos is failing to dedupe because of this? If so any ideas how I prevent this happening and just so the two intended data points?

**Comment by brian-brazil** [comment]
I can't help you with Thanos questions, but nothing here indicates a bug in the cloudwatch exportrer.

**Comment by TheComice** [comment]
Ok thanks. Should I move the question to the Thanos forum?

**Comment by brian-brazil** [comment]
If you're suspecting Thanos is messing with the data, then that would seem appropriate. There's not however enough information to indicate anything is going wrong at any level.

**Comment by anas-aso** [comment]
@TheComice this might be due to Prometheus `query.lookback-delta` config. If you fetch the results from the exporter directly, you will not see any duplicated values, but if you query them from Prometheus (or Thanos), then you will keep seeing the last data point multiple times (depending on your `query.lookback-delta`) ... Normally you would see this behavior with metrics that appear & disappear, and since AWS CloudWatch reports most of its metrics ONLY if it has a non-zero value, you will end up in this situation.

**Comment by brian-brazil** [comment]
I'm still not seeing a potential issue here on the exporter side, so closing for now. Lookback delta should be unrelated here.
