### ISSUE TITLE
Support authentication with AWS_WEB_IDENTITY_TOKEN_FILE

### ISSUE THREAD

**Issue by james-callahan** [prometheus/cloudwatch_exporter#294]
Use IAM Service Account roles results in the environment variables `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` which should be usable for auth.

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#pod-configuration

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

This project appears to be using a new enough SDK, so probably something wrong with the way it is initialised?

**Comment by agung-kargo** [comment]
I also have the same problem with @james-callahan. Somehow my prometheus-cloudwatch-exporter not using those env vars (AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE). Instead it uses the ec2 instance profile (my EKS ec2).

**Comment by brian-brazil** [comment]
We don't support taking configuration from the environment - only the config file, so anything like this is up the the AWS library.

**Comment by james-callahan** [comment]
> We don't support taking configuration from the environment - only the config file, so anything like this is up the the AWS library.

I believe the issue is in the way that the AWS library is being initialised. 

e.g. use [`DefaultAWSCredentialsProviderChain`](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default)

**Comment by brian-brazil** [comment]
The 15 or so different AWS auth mechanisms are very challenging to support all of in a generic way, and when in the past something was tweaked to support one of them another of them usually broke. If we're going to risk another change, then it should be based off official docs of what simple of piece of code will support everything both now and in the future.

**Comment by agung-kargo** [comment]
Just an update, I managed to run this succesfully using `AWS_WEB_IDENTITY_TOKEN_FILE` (which automatically being injected by EKS).
Using [helm chart](https://github.com/helm/charts/tree/master/stable/prometheus-cloudwatch-exporter#prerequisites) to install this. Turns out the issue can be solved by setting up the same value for `fsGroup` and `runAsUser` 

> Or an IAM Role for service account attached to a service account with an annotation. If you run the pod as nobody in securityContext.runAsUser then also set securityContext.fsGroup to the same value so it will be able to access to the mounted secret.

**Comment by brian-brazil** [comment]
Great, so not an issue on our end.

**Comment by abjrcode** [comment]
> Just an update, I managed to run this succesfully using `AWS_WEB_IDENTITY_TOKEN_FILE` (which automatically being injected by EKS).
> Using [helm chart](https://github.com/helm/charts/tree/master/stable/prometheus-cloudwatch-exporter#prerequisites) to install this. Turns out the issue can be solved by setting up the same value for `fsGroup` and `runAsUser`
> 
> > Or an IAM Role for service account attached to a service account with an annotation. If you run the pod as nobody in securityContext.runAsUser then also set securityContext.fsGroup to the same value so it will be able to access to the mounted secret.

Hi @agung-kargo . Do you mind sharing your Helm chart configuration?
I have tried all kinds of combinations but the Pod's health check keeps failing _( I don't see any logs )_ and then its stuck in a crash loop.
