### ISSUE TITLE
[latest] Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by mandarg** [prometheus/cloudwatch_exporter#310]
I'm running the `latest` [image](https://hub.docker.com/layers/prom/cloudwatch-exporter/latest/images/sha256-74ad197210aed00145de2e6ebf24bf699ffc2de4c3d352c9c745ee7f4e77fd5d?context=explore)from Docker Hub (DIGEST:sha256:74ad197210aed00145de2e6ebf24bf699ffc2de4c3d352c9c745ee7f4e77fd5d) – and get the following errors on startup.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".                                                      
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

The application seems to still scrape CloudWatch, but I'm unable to debug properly due to the logging. Any way in which I can help with this? 

The [referenced link](http://www.slf4j.org/codes.html#StaticLoggerBinder) in the error message tells me:

> This happens when no appropriate SLF4J binding could be found on the class path.

...which makes sense – but I don't understand why SLF4J is expected there in the first place. It's not in the [list of dependencies](https://github.com/prometheus/cloudwatch_exporter/blob/ef0a8acfe1ee5b3f44ba024ddc2b75701d6aea73/pom.xml) as of ef0a8acf. Perhaps an issue with downstream dependencies, or the artifacts pushed to Maven?

**Comment by brian-brazil** [comment]
I get the same with a fresh build, but not the most recent release so this is likely the AWS v2 libraries breaking something.

**Comment by brian-brazil** [comment]
#317 should have fixed this.
