### ISSUE TITLE
Add a health check endpoint

### ISSUE THREAD

**Issue by Luzifer** [prometheus/cloudwatch_exporter#32]
> As a user of the CloudWatch exporter I want to be able to deploy the exporter on ECS behind an ELB without burning money at huge scale

**Current situation**

- The ELB needs an health check endpoint which responds with `HTTP200`
- The only exposed path in the exporter is `/metrics`
- Every request against `/metrics` does CloudWatch calls
- Health checks (every 10s N CloudWatch requests) are expensive

**Expected situation**

- The ELB needs an health check endpoint which responds with `HTTP200`
- There is an exposed path `/status` which responds with `HTTP200` reporting everything is fine (at least the Java application is available to respond)
- Health check requests do not burn money
- (I don't need to explain the huge AWS bill to my boss 😄 )

**Comment by brian-brazil** [comment]
I'd suggest going with a simpler setup where you'd colocate the cloudwatch exporter with prometheus. 

We'd generally recommend not to put any load balancers in front of exporters, as they're just a potential failure mode.

**Comment by dene14** [comment]
Well, in some cases it's not true... Cloudwatch exporter is a typical microservice that people normally want to have hosted in docker.
For AWS it's ECS service and if you don't want to go too far with service discovery you should add it to ELB or ALB. If with ELB it's possible just to check if port open, with ALB (application load balancer) you have to define some handler...

So can we please have it at least for the time while this exporter is so dumb (no caching, no ability to control specific groups of metrics in request and etc)?
