### ISSUE TITLE
Not getting any metrics for my firehose or lambda resources 

### ISSUE THREAD

**Issue by duffar12** [prometheus/cloudwatch_exporter#320]
## Problem
* I am not getting any metrics from firehose or lambda
* I have checked in cloudwatch and there is definitely data for the metrics that I'm requesting
* I have checked against issue #268 and issue #273 and it is not the same issue as the ARN's for both lambda and firehose end with the dimension value e.g 
* * arn:aws:firehose:region-name:xxxxxxx:deliverystream/my-delivery-stream-name
* * arn:aws:region-name:xxxxxxxxx:function:my-function-name

#### Example of my firehose config 

        region: eu-west-2
        set_timestamp: false
        metrics:
         - aws_namespace: AWS/FireHose
           aws_metric_name: DeliveryToS3.DataFreshness
           aws_dimensions: [DeliveryStreamName]
           aws_statistics: [Maximum, Sum, Average]
           aws_tag_select:
               tag_selections:
                   environment: ["test"]
               resource_type_selection: "firehose:deliverystream"
               resource_id_dimension: DeliveryStreamName

#### output from ```aws cloudwatch list-metrics --namespace AWS/Firehose --metric-name DeliveryToS3.DataFreshness```

      {
       "Metrics": [
        {
            "Namespace": "AWS/Firehose",
            "MetricName": "DeliveryToS3.DataFreshness",
            "Dimensions": [
                {
                    "Name": "DeliveryStreamName",
                    "Value": "my-firehose-name"
                }
            ]
        },

#### What I am getting from the exporter
* I am getting the aws_resource_info data indicating that the exporter is finding the resource correctly. It just seems not to be exporting any metrics

      aws_resource_info{job="aws_firehose",instance="",arn="arn:aws:firehose:region:xxxx:deliverystream/my-firehose-name",delivery_stream_name="my-firehose-name",tag_environment="test"} 1.0

#### Lambda
* I am having the exact same issue with lambda. I get the resoure_info metrics but nothing else

#### What is working
* It works like a dream for Kinesis streams and Kinesis Analytics

**Comment by brian-brazil** [comment]
Does it work without the aws_tag_select? If so I'd presume another variant of #268.

**Comment by duffar12** [comment]
So for the lambda it works without tag select. But firehose does not seem to work under any circumstances

**Comment by brian-brazil** [comment]
What happens if you try to fetch the firehose metric values via the CLI?

**Comment by duffar12** [comment]
So weirdly I can't see any metrics via the CLI. Not even the metrics that are visible via the exporter. I've also tried pulling out these metrics with the python client, but also no joy. Is there anything tricky about getting them? This is my query. I've also tried running similar ones with the get_metric_data method. Notice that I'm querying Kinesis rather than firehose as that's the resource that already works in prometheus

     client.get_metric_statistics(
            Namespace='AWS/Kinesis',
            MetricName=metric,
            Dimensions=[
               {
                   'Name': dimension,
                   'Value': stream,
               },
            ],
            StartTime=dt.datetime.now() - dt.timedelta(seconds=24000),
            EndTime=dt.datetime.now() - dt.timedelta(seconds=600),
            Period=600,
            Statistics=['SampleCount', 'Sum', 'Average'],
            Unit='Seconds')

**Comment by brian-brazil** [comment]
The main difference I see there is that you're sending in a unit.

**Comment by duffar12** [comment]
Ahhh you're right. The units seem to be breaking it - I seem to be getting the metrics now anyways both through the exporter and through the python methods. Not quite sure why I wasn't getting anything before, but  I guess it was a data issue. Thanks for the help
