### ISSUE TITLE
Most recent 0.10.0 release has incorrect date (off by one year)

### ISSUE THREAD

**Issue by funkfunk** [prometheus/cloudwatch_exporter#325]
Hello,

The `0.10.0` release, released on 2021-01-25, erroneously lists the release date as 2020-01-25.

https://github.com/prometheus/cloudwatch_exporter/releases/tag/cloudwatch_exporter-0.10.0

Thank You

**Comment by matthiasr** [comment]
Good catch, I corrected the release!
