### ISSUE TITLE
Not able to open the rules.yml file by prometheus service 

### ISSUE THREAD

**Issue by manzajohn** [prometheus/cloudwatch_exporter#326]
Is there a different way to put rules for cloudwatch-exporter or is it same way like we do in the prometheus?
Any sample code will be helpfull @brian-brazil

**Comment by manzajohn** [comment]
Added below content in prometheus.yml
rule_files:
  - rules.yml
 
Below is my rules.yml i tried.
groups:
    - name: Cloudwatch
      rules:
         - alert: SQSNotProcessing
           expr: aws_sqs_approximate_number_of_messages_visible_maximum == 0
           for: 0m
           labels:
              severity: critical
           annotations:
              summary: 'Prometheus TSDB reload failures (instance {{ $labels.instance }})'
              description: 'Prometheus encountered {{ $value }} TSDB reload failures  VALUE = {{ $value }}  LABELS: {{ $labels }}'

**Comment by matthiasr** [comment]
I think there is some confusion about the roles of the different components here. The cloudwatch exporter does not read or evaluate Prometheus alert rules, this is by design. The exporter only transforms the current value of CloudWatch metrics into the Prometheus scrape format; these can then be collected by [Prometheus](https://github.com/prometheus/prometheus) or other metric systems.
Alerting rules, like the one you posted, are evaluated by Prometheus, not the exporter.

**Comment by manzajohn** [comment]
`global:
  scrape_interval: xs
  scrape_timeout: xs
  evaluation_interval: xs
  query_log_file: /var/log/prometheus/prometheus_query.log
rule_files:
      - cloudwatch_rules.yml
scrape_configs:

- job_name: cloudwatch-export-prometheus
  honor_timestamps: true
  honor_labels: true
  scrape_interval: xs
  scrape_timeout: xs
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: cloudwatch-export-scrape
  honor_timestamps: true
  honor_labels: true
  scrape_interval: 60s
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:5000

- job_name: cloudwatch-export-nodeexporter
  honor_timestamps: true
  honor_labels: true
  scrape_interval: xs
  scrape_timeout: xs
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9100

- job_name: alertmanager
  honor_timestamps: true
  honor_labels: true
  scrape_interval: xs
  scrape_timeout: xs
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - x.x.x.x:9093
    - x.x.x.x:9093`
Above is my prometheus configuration, in this i defined the rules file cloudwatch_rules.yml.
Below is the cloudwatch_rules.yml
`groups:
    - name: Cloudwatch
      rules:
           - alert: SQSNotProcessing
             expr: aws_sqs_approximate_age_of_oldest_message > x * x
             for: 1m
             labels:
                  severity: warning
             annotations:
                    summary: 'SQSNotProcessing  (instance {{ $labels.instance }})'
                    description: 'SQSNotProcessing  {{ $value }}  VALUE = {{ $value }}  LABELS: {{ $labels }}'
`
With these configuration when i start the prometheus service, its failing to load the /etc/prometheus/prometheus.yml file.so
the "rule_files:" block is correct? or the error is for cloudwatch_rules.yml?, please clarify
err="error loading config from \"/etc/prometheus/prometheus.yml\": one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/prometheus.yml\")"

**Comment by matthiasr** [comment]
Please ask Prometheus usage questions on the appropriate mailing ist (prometheus-users): https://prometheus.io/community/
