### ISSUE TITLE
cloudwatch_requests_total metric was missing intermittently in us-east-1 region

### ISSUE THREAD

**Issue by RajavigneshK** [prometheus/cloudwatch_exporter#327]
we had intermittent issue where metrics were scrapped on and off and metric: "cloudwatch_requests_total" was missing intermittently and got resolved automatically, but cloudwatch-exporter was running, this issue was created and getting resolved automatically in given a certain time interval
We faced this problem in two different accounts in us-east-1 region where cloudwatch-exporter service was running as docker, we didn't face this issue in us-west-2 region where we were running cloudwatch-exporter there too
I have attached the graph screenshots from both the accounts for metric: "cloudwatch_requests_total"
![non-prod](https://user-images.githubusercontent.com/20559052/110092358-8647a580-7dbf-11eb-95ce-dfdfee69df64.PNG)
![prod](https://user-images.githubusercontent.com/20559052/110092376-8b0c5980-7dbf-11eb-831c-76eafa0e7943.PNG)

**Comment by matthiasr** [comment]
Can you clarify whether only this metric was missing, or all metrics from
the exporter? What was the value of the `up` metric corresponding to this
target at the time? What did the exporter and Prometheus log while this was
happening?

**Comment by RajavigneshK** [comment]
We were having alert set for **absent** of this metric: cloudwatch_requests_total, so the alert got triggered at that time, Checked the other metric like CPU utilization, but there is no missing metric for those
I was unable to see any logs in cloudwatch_exporter at that time
In Prometheus also we doesn't have have any error logs at that time

**Comment by RajavigneshK** [comment]
Is cloudwatch_requests_total is a custom metric generated by cloudwatch_exporter service?

**Comment by matthiasr** [comment]
Yes, this is an internal metric. Because of the age of the issue, we will not be able to debug this further. If it happens again, please collect any log messages from Prometheus and the CloudWatch exporter, as well as the information on the target on Prometheus' targets page, including the error message if any.
