### ISSUE TITLE
cannot use custom metrics with prometheus adapter 

### ISSUE THREAD

**Issue by oussama-mechlaoui** [prometheus/cloudwatch_exporter#332]
I want to use cloudwatch prometheus metrics as custom metrics with prometheus-adapter. I have defined the custom rule in the adapter-config cm as follows:

    - metricsQuery: '{namespace!="",__name__=~"^aws_applicationelb_request_.*",load_balancer="app/k8s-eksmonitoring-1bb56c3370/16ae9f70d2e5fad4"}'
      name:
        as: ''
        matches: '^aws_(.*)_sum$'
      resources:
        overrides:
          namespace:
            resource: 'namespace'
          pod:
            resource: 'pod'
      seriesQuery: '{namespace!="",__name__=~"^aws_applicationelb_request_.*",load_balancer="app/k8s-eksmonitoring-1bb56c3370/16ae9f70d2e5fad4"}'

The list of custom metrics is empty.

kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ | jq .
{
"kind": "APIResourceList",
"apiVersion": "v1",
"groupVersion": "custom.metrics.k8s.io/v1beta1",
"resources": []
}

I have enabled debug for prometheus-adapter (v=10), I can see the following in the logs:

I0412 15:35:51.303854       1 api.go:74] GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/series?match%5B%5D=%7Bnamespace%21%3D%22%22%2C__name__%3D~%22%5Eaws_applicationelb_request_.%2A%22%2Cload_balancer%3D%22app%2Fk8s-eksmonitoring-1bb56c3370%2F16ae9f70d2e5fad4%22%7D&start=1618241691.302 200 OK
I0412 15:35:51.303924       1 api.go:93] Response Body: {"status":"success","data":[]}
I0412 15:35:51.303973       1 provider.go:279] Set available metric list from Prometheus to: [[]]

When I try to curl directly the prometheus-server, I with same query link generated by the adapter I get the following results:

curl -s http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/series?match%5B%5D=%7Bnamespace%21%3D%22%22%2C__name__%3D~%22%5Eaws_applicationelb_request_.%2A%22%2Cload_balancer%3D%22app%2Fk8s-eksmonitoring-1bb56c3370%2F16ae9f70d2e5fad4%22%7D | jq .                                           
{
  "status": "success",
  "data": [
    {
      "__name__": "aws_applicationelb_request_count_sum",
      "container": "prometheus-cloudwatch-exporter",
      "endpoint": "http",
      "exported_job": "aws_applicationelb",
      "instance": "192.168.2.127:9106",
      "job": "prometheus-cloudwatch-exporter",
      "load_balancer": "app/k8s-eksmonitoring-1bb56c3370/16ae9f70d2e5fad4",
      "namespace": "monitoring",
      "pod": "cw-prometheus-exporter-prometheus-cloudwatch-exporter-9fb7dc9ct",
      "service": "cw-prometheus-exporter-prometheus-cloudwatch-exporter"
    }
]
}

Any insights, how can I use cloudwatch metrics with prometheus-adapter?

**Comment by matthiasr** [comment]
Since the data is there in Prometheus, this does not seem like an issue with the exporter. Could you please ask this in the appropriate place, such as the prometheus-users mailing list? More people with experience using the adapter will be able to see it there.
