### ISSUE TITLE
configure multiple IAM accounts and multiple exporter programs

### ISSUE THREAD

**Issue by vincent-doudou** [prometheus/cloudwatch_exporter#336]
When I configure multiple IAM accounts and multiple exporter programs on a server, how can I ensure that the exporter program reads the corresponding IAM accounts?

**Comment by matthiasr** [comment]
The exporter doesn't do anything particular, unless you specify the `role_arn` configuration. You can leave that out, and instead use the standard [AWS SDK configuration](https://docs.aws.amazon.com/sdkref/latest/guide/overview.html) via [environment variables](https://docs.aws.amazon.com/sdkref/latest/guide/environment-variables.html) and/or [configuration files](https://docs.aws.amazon.com/sdkref/latest/guide/creds-config-files.html).

**Comment by matthiasr** [comment]
I'm going to close this issue since this is not really something I want the exporter to deal with at all (the SDK does it better). Feel free to reopen it if any of the standard mechanisms doesn't work with the exporter, but does work with the AWS CLI.
