### ISSUE TITLE
Export empty metrics as 0

### ISSUE THREAD

**Issue by jangrewe** [prometheus/cloudwatch_exporter#34]
Thanks for this exporter, it's really great to consolidate all metrics in one Prometheus instance!

I'm having an issue while setting up alerts, though: if there are no 5XX errors, that metrics isn't exported at all.

I was trying to calculate the error percentage by doing something like `aws_elb_httpcode_backend_5_xx_sum / aws_elb_request_count_sum`, but as the metric isn't exported, i don't get any data - not even 0.

Is this something that can be fixed? Thanks!

**Comment by brian-brazil** [comment]
If Cloudwatch doesn't export it, there's nothing we can really do as we have no data to work off.

**Comment by jangrewe** [comment]
Oh, right...
To be honest i haven't tested it yet, as i using Prometheus' graphs to build some "alert rule metrics", but maybe it works anyways ;-)
