### ISSUE TITLE
Metric help missing

### ISSUE THREAD

**Issue by chris-tw-m** [prometheus/cloudwatch_exporter#341]
Missing help in CloudWatch metric

```
# HELP aws_apigateway_count_sum CloudWatch metric AWS/ApiGateway Count Dimensions: null Statistic: Sum Unit: Count
# TYPE aws_apigateway_count_sum gauge
aws_apigateway_count_sum{job="aws_apigateway",instance="",} 13.0 1621310940000
```

I don't know where the number `1621310940000` come from. It seems to be an epoch timestamp. I hope to see the meaning inside the help. Let me know if I miss something.

**Comment by matthiasr** [comment]
The timestamp is part of the [Prometheus exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format). It is optional, in _most_ cases it is not there (so you may not have seen it before), but it is useful when bridging to another metric system like CloudWatch, which already made a measurement at some point in the past. It is not specific to any one metric, so it is not part of the metric description.

See also [this part of the README](https://github.com/prometheus/cloudwatch_exporter#timestamps) for more information on timestamps specifically for the exporter.

**Comment by chris-tw-m** [comment]
Thank you for your response.

It is helpful. Now I know more about Prometheus and Caveat of CloudWatch API.
