### ISSUE TITLE
Can I run it on AWS EKS

### ISSUE THREAD

**Issue by LetsCodeCloud** [prometheus/cloudwatch_exporter#342]
Hi Team

I want to test this with prometheus operator on AWS EKS cluster. I would like to export metrics via cloudwatch to AWS EKS Prometheus.
Could you please share how this can be achieved.

Thanks
Heera

**Comment by matthiasr** [comment]
Please use the appropriate [community channels](https://prometheus.io/community) for usage questions.

In general, the answer to your question is yes, there should be no problem running the [Docker image](https://github.com/prometheus/cloudwatch_exporter#docker-image) in Kubernetes like any other app.
