### ISSUE TITLE
Automatically determine `aws_dimensions`

### ISSUE THREAD

**Issue by matthiasr** [prometheus/cloudwatch_exporter#351]
cf. #350 https://github.com/prometheus/cloudwatch_exporter/issues/237#issuecomment-581895552

There is no leeway for users in this. Instead of relying on the user to specify the dimensions, make this automatic.

**Comment by brian-brazil** [comment]
It's valid for users not to want all dimensions for cardinality, correctness, performance, and cost reasons.

**Comment by matthiasr** [comment]
Hmm, fair. I wonder how we can make it more user-friendly for the cases like this where _not_ specifying _just_ the right dimensions won't return anything?

**Comment by brian-brazil** [comment]
There's not much you can do I think, at the end of the day the config is mirroring the cloudwatch API and extra requests aren't free - plus if it were correctly returning nothing (say if you didn't use a give service) doing magic would likely cause even more confusion.

**Comment by brian-brazil** [comment]
The general approach I took to this was to encourage users to add working examples to the example.yml in this repo, as unfortunately it's all on a service by service basis.

**Comment by matthiasr** [comment]
See also #356 for a more general request for more automatic discovery.

**Comment by dragoangel** [comment]
Hi, what if allow some sort of tempting the configs in foreach way or using wildcards.

Wildcard: give me all metrics in Namespace X and use for all of them Dimension Y:
```

**Comment by dragoangel** [comment]
Hi, what if allow some sort of tempting the configs in foreach way or using wildcards.

Wildcard options:
1. give me all metrics in Namespace X and use for all of them Dimension Y:
```
- aws_namespace: AWS/NetworkELB
  aws_metric_name: *
  aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
  aws_statistics: [Average]
```
2. give me all metrics in Namespace X* with name Y:
```
- aws_namespace: Project-*
  aws_metric_name: Info-Logs-Counter
  aws_statistics: [Sum]
```

Foreach:
Imagine we have:
```
- var_name: Environment
  var_values: [SBX, DEV, STG, PRD]

- var_name: Service
  var_values: [Identity, DataProvider, Media]

- var_name: LogLevel
  var_values: [Info, Warning, Error]
```
And we need write how much code to describe all this? 🤔
Well here foreach come in play:
```
- aws_namespace: MyService-${Environment}-${Service}
  aws_metric_name: ${LogLevel}-Logs-Counter
  aws_statistics: [Sum]
```

**Comment by djloude** [comment]
[Commented this on another issue](https://github.com/prometheus/cloudwatch_exporter/issues/356#issuecomment-995023435) but the functionality of the scripts and playbook add all the available aws_dimensions when it creates the cloudwatch.yml file.

**Comment by matthiasr** [comment]
I'll close this issue as #394 solves the immediate need, and is as far as I want to go at this point.
