### ISSUE TITLE
What are the possible values for `resource_type_selection`?

### ISSUE THREAD

**Issue by bugok** [prometheus/cloudwatch_exporter#353]
The documentation points to this page: https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#genref-aws-service-namesspaces

However, there isn't a list of resource types I could find there. 

Am I missing something? Where can I find a list of the possible values?

Thanks.

**Comment by bugok** [comment]
Maybe this? 

https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html

**Comment by matthiasr** [comment]
If I understand this correctly, the first link defines resource types as the last part of the ARN. This is an ever-expanding set as AWS releases new features.

I don't think the second link is relevant, it's about what resource types _AWS Config_ supports.

**Comment by matthiasr** [comment]
I think this is something we should document better.

**Comment by matthiasr** [comment]
This was done in #368.
