### ISSUE TITLE
Use only semver as image tag

### ISSUE THREAD

**Issue by czunker** [prometheus/cloudwatch_exporter#354]
Currently, images on Docker hub are tagged like this:
```
prom/cloudwatch-exporter:cloudwatch_exporter-0.11.0
```
It would be nice, when it would look like this:
```
prom/cloudwatch-exporter:0.11.0
```

This tag should then also be pushed to quay.io which currently only has latest.

**Comment by czunker** [comment]
There was already a similar ticket which got closed without comment: #76 
Still think, this would be a good practice to reduce the tag to only the semver.

**Comment by czunker** [comment]
I could only find the [CircleCI config](https://github.com/prometheus/cloudwatch_exporter/blob/master/.circleci/config.yml) which pushes latest to quay.io. I couldn't find anything about the pushes to Docker hub.

**Comment by matthiasr** [comment]
Unfortunately my knowledge of the whole release process is shaky as well. I managed to do it once but I don't remember what happened with Docker 😔 Maybe the maven release plugin built it?

**Comment by universam1** [comment]
Actually this should be considered a bug - we are relying on renovate-bot and this is the only tag where we see this exception:

```
DEBUG: Dependency prom/cloudwatch-exporter has unsupported value cloudwatch_exporter-0.9.0 (repository=o11n/eks)
```
Hence, we are unable to automate the depency upgrade because of this circumstance

**Comment by matthiasr** [comment]
As a first step, I am changing the Maven tag format to the `v0.11.0` form. This is the form we use in other Prometheus projects, including the `v`, so I want to also use it here.

**Comment by matthiasr** [comment]
Please see and comment on #378 – this should™ start automatically publishing tagged versions to both Quay and Docker Hub, as well as clarify the README on this.

**Comment by czunker** [comment]
Thanks for fixing this!
