### ISSUE TITLE
Long scrape duration with large volume of metrics 

### ISSUE THREAD

**Issue by caryjpaepen** [prometheus/cloudwatch_exporter#355]
Hi there, we have a large volume of metrics in CloudWatch, and we are getting timeouts when using the exporter. Currently metrics are being pulled in a single thread, is there any plan to switch to a multithreaded approach where metrics are pulled concurrently?

**Comment by caryjpaepen** [comment]
To provide some context:
- We have seen an increasing number of timeouts as we gradually add more metrics to our configs during many years of use. This is not a problem that suddenly appeared.
- As an example, in one of our regions, we are pulling around 700 metrics (declared as 12 different metrics in the config each having 3 statistics and 3 dimensions) , the scrape duration is around 45s (while our Prometheus timeout limit is 25s).

**Comment by matthiasr** [comment]
I believe #134 would help with this. There have been some efforts to tackle this, but unfortunately they stalled (#186, #301).

I am going to close this issue as a duplicate, but would welcome contributions that tackle this 😃
