### ISSUE TITLE
Metrics output contains 2 values

### ISSUE THREAD

**Issue by ashishvaishno** [prometheus/cloudwatch_exporter#364]
Hello,

I am able to scrape the metrics using cloudwatch exporter, but i see 2 values at the end. 
Example :
```aws_elb_request_count_sum{job="aws_elb",instance="",load_balancer_name="xxxxx",availability_zone="eu-central-1b",} 1.0 1633099560000```

is these values ```1.0 1633099560000``` correct? Shouldn't I just see one value?

Regards
Ashish

**Comment by eugenberend** [comment]
@ashishvaishno Hi, how did you solve this?

**Comment by sanadhis** [comment]
hi I have also encountered this issue? any help here?
