### ISSUE TITLE
Add new S3 metric to cloudwatch exporter

### ISSUE THREAD

**Issue by erdong** [prometheus/cloudwatch_exporter#370]
In Sep 17, 2021 , Amazon CloudWatch request metrics for Amazon S3 Access Points now available .

There was only BucketSizeBytes and NumberOfObjects before , and now request metrics、replication metrics、Amazon S3 on Outposts CloudWatch metrics available .

Metrics like GetRequests 、PutRequests  are very important to S3, Can you add these new metrics to cloudwatch_exporter ?

I've been using cloudwatch exporter for over a year now and it works really well. It helped me unify the data sources, and I could look up all kinds of data in Prometheus.

# Refer to the link
https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-cloudwatch-metrics-s3-access-points/?nc1=h_ls

https://docs.aws.amazon.com/AmazonS3/latest/userguide/metrics-dimensions.html

**Comment by chakch** [comment]
Hi @erdong  ,
You can retrieve this metrics using the version 0.11.0 of the exporter. You can use the following example:
  - aws_namespace: AWS/S3
    aws_metric_name: GetRequests
    aws_dimensions: [BucketName,FilterId]
    set_timestamp: false
    range_seconds: 172800
    period_seconds: 86400

**Comment by matthiasr** [comment]
As of #381 this is also in the S3 example file: https://github.com/prometheus/cloudwatch_exporter/blob/1391089f4dd093c0f4e70cf5c9e994792c70701d/examples/S3.yml#L75-L81

**Comment by erdong** [comment]
Thanks, I can collect this data, and it's working fine now.
