### ISSUE TITLE
Update to Jetty 11

### ISSUE THREAD

**Issue by matthiasr** [prometheus/cloudwatch_exporter#390]
Follow-up to #389: update to Jetty 11, and follow the javax -> jakarta transition.

**Comment by jerry-shao** [comment]
Looks like `io.prometheus.simpleclient` is still using javax, so just bumping up the dependency version and replace javax with jakarta here won't work.

**Comment by mindw** [comment]
Perhaps switching to https://github.com/prometheus/client_java/tree/master/simpleclient_servlet_jakarta is a solution?
