### ISSUE TITLE
very SLOW scraping: 10 minutes latency

### ISSUE THREAD

**Issue by ofiry-tm** [prometheus/cloudwatch_exporter#396]

**Comment by ofiry-tm** [comment]
I actually getting a 10 minutes latency,
meaning: 10 minutes go by from the time i see the cloudwatch metrics updated untill the cloudwatch exporter export it.

**Comment by matthiasr** [comment]
This is [a feature](https://github.com/prometheus/cloudwatch_exporter#timestamps), not a bug. 

There is a fundamental mismatch between the metric models of CloudWatch and Prometheus: CW metrics converge over a period of up to 10 minutes, so the metric value at a specific time T will keep changing until up to T+10min.

Prometheus, on the other hand, considers a scraped value final – at T+10min, we can no longer reach back and "correct" the value at T.

The exporter, works around this by "hiding" the value until it is guaranteed to be correct, delaying all metrics by 10 minutes. This is configurable, but you risk recording incorrect data in your Prometheus metrics.

It is unfortunate, but there is no way for Prometheus to know the true value sooner.

**Comment by ofiry-tm** [comment]
> The exporter, works around this by "hiding" the value until it is guaranteed to be correct, delaying all metrics by 10 minutes. This is configurable, but you risk recording incorrect data in your Prometheus metrics.

how is it configurable ?

**Comment by matthiasr** [comment]
Using the [`delay_seconds`](https://github.com/prometheus/cloudwatch_exporter#timestamps) configuration setting, either globally or per metric.

**Comment by ofiry-tm** [comment]
> Using the [`delay_seconds`](https://github.com/prometheus/cloudwatch_exporter#timestamps) configuration setting, either globally or per metric.

Thanks.

the default is 600s,
so if I change it to 60s, will it make X10 more requests to cloudwatch ?

**Comment by matthiasr** [comment]
No, the exporter requests metrics more frequently, it only asks for data from 10 minutes ago
