### ISSUE TITLE
Question: Export custom namespace metrics 

### ISSUE THREAD

**Issue by shraddhabhise** [prometheus/cloudwatch_exporter#399]
Hi, 

I would like to export metrics under the custom namespaces in CloudWatch. I have a question:
1: For e.g. the **metric "M"** is under the the **namespace "X"** with the **schema "metrics with no dimensions"** and this namespace does not belong to AWS namespaces. How can the example config file look in this case?

It will be really great if someone can help me with the example.

Thanks
Regards,
Shraddha Bhise

**Comment by matthiasr** [comment]
Hi, can you please ask this question in one of the [community channels](https://prometheus.io/community)? There's a lot more people with a lot more diverse use cases there, so the chance that someone knows the answer is much higher.
