### ISSUE TITLE
Good example prometheus dashboard someone can recommend?

### ISSUE THREAD

**Issue by WilliamCassanova** [prometheus/cloudwatch_exporter#408]
More of a question than an issue....Does someone know of a good starter prometheus dashboard that can be used with the metrics exposed by the cloudwatch exporter?  I am looking mainly for something that shows AWS/ApplicationELB metrics only.

I have looked at:
- https://grafana.com/grafana/dashboards/10925 which seems to have some information specfic to billing
- https://grafana.com/grafana/dashboards/590 which seems to require cloudwatch itself as a datasource.

**Comment by K890** [comment]
@WilliamCassanova Did you find anything? 
https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards is something that I stumbled upon but it uses cloudwatch as the datasource itself. Not really useful for cloudwatch_exporter.

**Comment by WilliamCassanova** [comment]
I did not.  But the link provided may prove helpful.  We sorta paused on this for a bit but picking it back up soon.
