### ISSUE TITLE
Vulnerable Java Version

### ISSUE THREAD

**Issue by citosid** [prometheus/cloudwatch_exporter#409]
Dear developers,

Thank you so much for your awesome work with this tool! We've been using it in our k8s clusters and it has proven to be really useful for us.

We have a few of systems that allow us to monitor the traffic inside the network and look for weird or suspicious behavior. And it triggered an alert saying this container is using a vulnerable version of Java (version 17). 

I was able to find this list of vulnerabilities in Java 17: https://vulmon.com/searchpage?q=oracle+openjdk+17

Have you received similar alerts? Do you have plans to update to a newer version of Java in the future?

**Extra information**

The tool that triggered the alert is suricata, and the exact alert is:

> alert http $HOME_NET any -> $EXTERNAL_NET any (msg:"ET POLICY Vulnerable Java Version 17.0.x Detected"; flow:established,to_server; flowbits:set,ET.http.javaclient.vulnerable; threshold: type limit, count 2, seconds 300, track by_src; http.user_agent; content:"Java/17.0."; content:!"1"; within:1; reference:url,www.oracle.com/java/technologies/javase/17u-relnotes.html; classtype:bad-unknown; sid:2034817; rev:2; metadata:affected_product Java, attack_target Client_Endpoint, created_at 2021_12_21, deployment Perimeter, former_category POLICY, signature_severity Informational, updated_at 2021_12_22;)

It was added here: https://www.proofpoint.com/us/daily-ruleset-update-summary-20211222

Thank you so much again for all your help providing this awesome tool!

Look forward to your comments.

**Comment by matthiasr** [comment]
Thank you! We normally get the latest patch version whenever we build a release. Is there any vulnerability in particular that you are concerned about?

**Comment by matthiasr** [comment]
I just made a release with JDK 17.0.2 since Temurin has not released 17.0.3 yet. To track that update, let's use #415.
