### ISSUE TITLE
ELB/ALB metrics not available

### ISSUE THREAD

**Issue by garryknox** [prometheus/cloudwatch_exporter#41]
The current version doesn't support the new Application Load Balancer metrics. We migrated our Load Balancers from the Classic version to the new ALB and all of our metrics disappeared.

 I used the following config which is similar to the example in the Readme. 

---
region: us-east-1
metrics:
 - aws_namespace: AWS/ELB
   aws_metric_name: RequestCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]

 
 I do have  data in the Cloudwatch dashboard.

 Adding the new TargetGroup dimension results in no data being returned even Classic Load Balancer metrics.

**Comment by brian-brazil** [comment]
Are you aware that the namespace is different? http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html

**Comment by garryknox** [comment]
That was it. Made the change and it worked. Awesome, thanks for the quick reply Brian!

**Comment by brian-brazil** [comment]
No problem, if you could send a PR for the additional metric names that'd be appreciated.

**Comment by davislhidc** [comment]
The Target Group dimension still results in no data being returned?
