### ISSUE TITLE
Unify and enforce formatting

### ISSUE THREAD

**Issue by matthiasr** [prometheus/cloudwatch_exporter#417]
This came up in [#414](https://github.com/prometheus/cloudwatch_exporter/pull/414#issuecomment-1108298222) and I ran into it a few times.

Unified and automatically formatable styling makes it easier for different contributors to work on the code. Instead of piece-meal changes that make individual PRs difficult to follow, I would like to do one big bang reformat, ideally while there are no other open PRs.

What are the most common formatters? Ideally we should not require any special setup from users with auto-formatting IDEs. At the least, users of (say) IntelliJ, Eclipse, and VS Code don't need to do anything to stop their editor from enforcing the wrong format; better would be if these also automatically enforce the _right_ format.

In any case, we should enforce this formatting in PR pipelines, probably in a separate job for clarity.

**Comment by matthiasr** [comment]
cc @or-shachar because I am sure you have opinions on this 😄

**Comment by or-shachar** [comment]
I made a little research and  came up with #418 
I do want #414 to be merged first so I won't have serious conflicts :)
