### ISSUE TITLE
example ec2 not valid

### ISSUE THREAD

**Issue by GreenRover** [prometheus/cloudwatch_exporter#430]
The prometheus validator fails here cause:
`error while linting: text format parsing error in line 2153: second HELP line for metric name "aws_ec2_cpucredit_usage_average"`

Please remote the duplicated entry:
https://github.com/prometheus/cloudwatch_exporter/blob/master/examples/EC2.yml#L56
https://github.com/prometheus/cloudwatch_exporter/blob/master/examples/EC2.yml#L62

**Comment by matthiasr** [comment]
Good catch, would you mind making a PR?

**Comment by or-shachar** [comment]
@matthiasr should we close this one?

**Comment by matthiasr** [comment]
Ah indeed, this was fixed in #433
