### ISSUE TITLE
What is the cpu / memory / size footprint of this program ?

### ISSUE THREAD

**Issue by abourget** [prometheus/cloudwatch_exporter#44]
Just wondering, because its java backed, what's the memory use and Docker image size for this program ?

**Comment by brian-brazil** [comment]
I haven't measured it, but I imagine it's quite small.

**Comment by Rudd-O** [comment]
Our limits are 384M for RAM.  Doesn't seem to be a problem.  Less than that and it gets SEGV'd by the container limit.
