### ISSUE TITLE
Cache result of ListMetrics calls

### ISSUE THREAD

**Issue by krzysztof-magosa** [prometheus/cloudwatch_exporter#449]
# Proposal
###  Use case. Why is this important?

In my opinion calling ListMetrics every minute is waste of money - resources aren't created and removed so often. To avoid that caching could be implemented with configurable TTL. In our use case we generate about 6 times more ListMetrics than GetMetricData requests, and they both are charged same way, so that would be huge money saver.

### How do you think the new configuration should look like?

Example:
```yaml
list_metrics_cache_ttl: 5m
```

**Comment by matthiasr** [comment]
Yes, that's a great idea!

**Comment by matthiasr** [comment]
What should the default be? Preserve the current behavior, or can we settle on a reasonable default?

**Comment by krzysztof-magosa** [comment]
In my opinion 5m could be safe default - if you poll CW every 1 minute, that will save 80% of ListMetrics calls without excessive time needed for exporter to see new resources.

**Comment by krzysztof-magosa** [comment]
Seems it has been implemented by @mtt88 in #453. Thanks!
I'll test functionality and close issue if it works fine.

**Comment by krzysztof-magosa** [comment]
![image](https://user-images.githubusercontent.com/6112411/191024565-fa566373-7ae4-49a8-89c3-fc9df5a44dea.png)

All good, TTL is set to 60 minutes on above screen.
That will make huge difference on AWS bills, many thanks again.
