### ISSUE TITLE
I can't see metrics values in prometheus

### ISSUE THREAD

**Issue by rubenssoto** [prometheus/cloudwatch_exporter#451]
Hello everyone,

Thank you for this amazing exporter. Probably I am doing something wrong. I need to export some metrics from AWS MSK. I used prometheus exporter helm chart from prometheus community repo.

My metrics config:

region: us-west-2
  period_seconds: 240
  metrics:
  - aws_namespace: AWS/Kafka
    aws_metric_name: MemoryUsed
    aws_dimensions: [Cluster Name, Broker ID]

my service monitor config

serviceMonitor:
  # When set true then use a ServiceMonitor to configure scraping
  enabled: true
  namespace: monitoring
  interval: 30s
  telemetryPath: /metrics
  timeout: 10s
  
  I can see the metrics on cloudwatch exporter endpoint but I cant see in prometheus, the service monitor is enabled
  
<img width="1792" alt="Captura de Tela 2022-08-17 às 16 46 13" src="https://user-images.githubusercontent.com/36298331/185229212-6ec13b1c-83c6-4848-bcdc-f624ce800408.png">
<img width="1792" alt="Captura de Tela 2022-08-17 às 16 45 50" src="https://user-images.githubusercontent.com/36298331/185229227-8362a6cd-db10-400c-807a-b7a4229553d8.png">
<img width="1792" alt="Captura de Tela 2022-08-17 às 16 45 26" src="https://user-images.githubusercontent.com/36298331/185229232-84fb14ae-fb61-458e-8262-97d25c1e35c7.png">

**Comment by matthiasr** [comment]
Do the metrics show up in the graph view? Could this be due to the default `delay_seconds` (10 minutes)? Unfortunately CloudWatch metrics only converge after a while, while Prometheus samples are immutable, so the exporter has to (usually) report data from some time in the past.

**Comment by mr-coveros** [comment]
Same issue.  The cloudwatch-exporter is deployed with prometheus as sub-chart.  Deployed servicemonitor which gets picked up by prometheus servicediscovery, but (0 / 46 active targets).  None of the exposed metrics from cloudwatch-exporter ever show up in prometheus.
How do we get cloudwatch-exporter metrics to show up in prometheus?

**Comment by matthiasr** [comment]
@mr-coveros if the exporter isn't being discovered, something is not working at the discovery stage, which is different from @rubenssoto's problem. Looking at [this troubleshooting document](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md#troubleshooting-servicemonitor-changes), a common issue is port name mismatches.

**Comment by matthiasr** [comment]
Since the metrics show up in the exporter, this isn't an exporter issue, so I'll close this one to avoid distracting others from unrelated configuration issues.
