### ISSUE TITLE
[bug]: OpenSearch metrics not appearing on the exporter

### ISSUE THREAD

**Issue by deanb-everc** [prometheus/cloudwatch_exporter#452]
### What did you do
Please provide steps for us to reproduce this issue? Example for config file are very welcomed!

We are using the cloudwatch exporter helm chart to get our metrics to prometheus, our alerts are based on those metrics and so far everything worked fine. I tried to connect OpenSearch metrics to the exporter so we could use them in our alerting system.

metric name: ClusterStatus.green

link to aws docs:
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-cloudwatchmetrics.html#managedomains-cloudwatchmetrics-cluster-metrics

i added the metrics using this config to the config file:

  - aws_namespace: AWS/ES
    aws_metric_name: ClusterStatus.green
    aws_dimensions: [DomainName]
    aws_statistics: [Maximum]

i made sure that these metrics appear on cloudwatch:

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/111513416/185405501-7e153b39-48df-4104-9ff7-b34015bda950.png">

### What did you expect to see?

I expected the metrics to appear on the exporter

### What did you see instead? Under which circumstances?

The metrics do not appear on the exporter, although the configmap which contains the relevant metrics was updated, and the OS can see the new config:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/111513416/185405244-7eae321e-e371-4b3e-9079-ac3a6d751905.png">

### Are you currently working around this issue?
How are you currently solving this problem?

currently I didn't find a solution for this.

### Additional context
Anything else we should know?

Any chance to get some help with this?

### Attachments
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Environment

Using the official helm chart.

* Exporter version: `X.X.X`
* Operating system & architecture: `XX` 
* Running in containers? **y**
* Using the official image? **y**

### Exporter configuration file
<details>
<summary>expand</summary>

```yaml

```
</details>

### Logs

<details>
<summary>expand</summary>

```
(paste log lines here)
```
</details>

**Comment by deanb-everc** [comment]
nvm, found this and it worked:
https://github.com/prometheus/cloudwatch_exporter/issues/60

**Comment by raman0914** [comment]
Can you please share the example . How it worked. I’m facing the same issue @deanb-everc  please!

**Comment by raman0914** [comment]
did you get any example? @matthiasr

**Comment by raman0914** [comment]
> nvm, found this and it worked: #60

can you please explain or help!! what helped for you, please. i'm facing the same problem
