### ISSUE TITLE
[question]: How to get CW metrics from only a single resource

### ISSUE THREAD

**Issue by tomiszili** [prometheus/cloudwatch_exporter#457]
Hello!

How to set the configuration to retrieve CW metrics for a single resource with the ID or arn of the resource. (e.g.: ec2)?

Thanks in advance!

**Comment by matthiasr** [comment]
I think something like

```yaml
aws_dimension_select:
  InstanceId: i-123456
```

should work? Unfortunately you will have to specify this for each of the metrics you want to collect, such as those in [this example](https://github.com/prometheus/cloudwatch_exporter/blob/master/examples/EC2.yml).

In general, usage questions are better directed at the [community channels](https://prometheus.io/community) where more people can help – I'm sure someone on the mailing lists or in chat has the same use case.
