### ISSUE TITLE
[request]: Ability to expand environment variables in config file

### ISSUE THREAD

**Issue by peterpakos** [prometheus/cloudwatch_exporter#467]
# Proposal
###  Use case. Why is this important?

We are running multiple cloudwatch exporter instances to collect metrics from multiple AWS accounts.

Apart from `region` and `role_arn` settings, those configuration files are identical.

It would reduce the overhead of maintaining multiple setups if we could have a single configuration file with variables passed for `region` and `role_arn`.

**Comment by matthiasr** [comment]
In general, the Prometheus project is very hesitant to add this as a general ability. It opens all kinds of complexities in configuration handling.

In _particular_ however, I believe you can achieve this specific use case already. The basic idea is not to specify any authentication- or region-related options in the configuration file, and instead configuring the AWS (Java) SDK through the environment directly. Unfortunately this does involve a file one way or the other:

- use web identity token authentication, and specify `AWS_REGION` and `AWS_ROLE_ARN`
- use traditional authentication, supply the possible roles as a configuration file, and specify `AWS_REGION` and `AWS_PROFILE`

How to do this depends on your runtime environment. I hope this helps!
