### ISSUE TITLE
Not getting EC2 data

### ISSUE THREAD

**Issue by AnthonyWC** [prometheus/cloudwatch_exporter#50]
I have setup the cloudwatch exporter using the default template and I can get ELB & Elasticache data but I don't get any EC2 data when I add the following:

```
- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
```
I do get data if I run: aws cloudwatch list-metrics --namespace AWS/EC2 --metric-name CPUUtilization

So what I am doing wrong?

Also beside the example.yml, is there a template that cover most/all of the other name space?

**Comment by brian-brazil** [comment]
Have you configured the correct region? Have you tried passing that dimension to the CLI?

AWS docs are where this is all documented.

**Comment by AnthonyWC** [comment]
Actually never-mind, it is working.  I didn't see the time period in the grafana dashboard to select the time period.

But I am curious as to why doesn't the various cloudwatch metric names show up in cloudwatch exporter metric url?  E.g. Cloudwatch exporter main url there is a "Metrics" url, if I click on it, it shows various metric but none of them is prefixed with "aws_" but I can see the cloudwatch metric within prometheus browser.
