### ISSUE TITLE
[bug]: Can't scrape from kubernetes pod

### ISSUE THREAD

**Issue by saamrezaei** [prometheus/cloudwatch_exporter#519]
### What did you do

I've created a docker image that will execute the jar file using my own config file. This docker image gets deployed to a kubernetes cluster as a pod with a service account specifying the assumed role. I also specify the "role_arn" field in the config file. I have confirmed that my environment variables (shown below) are all appropriately assigned within the pod. I've confirmed the service account namespace and service account name within the trust relationship of the iam role match the kubernetes service account config. However, inside the logs of the pod, I am still receiving the error shown below. Has anyone run into a similar issue? Wondering if this has something to do with the credentials chain you guys use in the implementation or if it's related to the aws role on my end. 

AWS_DEFAULT_REGION
AWS_WEB_IDENTITY_TOKEN_FILE
AWS_REGION
AWS_ROLE_ARN

![image](https://user-images.githubusercontent.com/99278771/226723311-9633ca29-512b-4adb-9589-32be9e702a13.png)

**Comment by matthiasr** [comment]
Hmm, this is nearly impossible to debug without a lot more information. Things I would look at:

Do equivalent actions work when using the AWS CLI from within the container (with `kubectl exec`)?

Do you have any auth related configuration in your configuration _file_? Specifically, if you have a `role_arn` in the configuration, we do [more setup](https://github.com/prometheus/cloudwatch_exporter/blob/1d551c4ebacc3944154ab382343e7be2adbee71a/src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java#L191-L193), whereas if you don't specify anything, we instantiate the CloudWatch client with the SDK defaults, and you can use environment variables to configure it. Trying to do both doesn't always work super well.

**Comment by saamrezaei** [comment]
Ended up fixing that issue, didn't realize I was using an older version of the pre-built jar.

I got past the auth error, however, im still not receiving any metrics in prometheus. These are the only logs present in the pod
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/99278771/232573334-2b792131-2f34-4767-9f82-bcdff3a9b3c3.png">

Looking at the web endpoint, I see the following, indicating it is attempting pull metrics, however I dont see anything else relating to my metrics inside the web endpoint. 
    - cloudwatch_requests_total{action="listMetrics",namespace="AWS/Kinesis",} 22.0


My current config looks like this (following the example kinesis exporter), with the region and assumed role coming from the environment variables of the pod

![image](https://user-images.githubusercontent.com/99278771/232573724-e5d4e6af-0e2f-4830-95c0-a61e232ebf41.png)

Any ideas on where to look to debug this?

**Comment by matthiasr** [comment]
Interesting, it certainly shouldn't fail like that 😅 Something unexpected is happening with your `dimensions`, can you share your configuration?

**Comment by saamrezaei** [comment]
![image](https://user-images.githubusercontent.com/99278771/233094007-e795976d-9185-4e02-8e21-1f4bef20d696.png)

**Comment by saamrezaei** [comment]
Fixed it with this config.yaml set up
![image](https://user-images.githubusercontent.com/99278771/233392746-2d917857-c304-45ea-97f3-a635c99b4d3e.png)
