### ISSUE TITLE
Docker images don't have tags

### ISSUE THREAD

**Issue by binman-docker** [prometheus/cloudwatch_exporter#53]
It looks like prom/cloudwatch-exporter in Hub is set to autobuild from master on this repository, and to tag the image as latest: https://hub.docker.com/r/prom/cloudwatch-exporter/builds/

If latest is the only tag available, there's no way to guarantee that two containers using the "latest" tag are actually running the same code. This is also a problem if you build your own container using "FROM prom/cloudwatch-exporter" - no way to guarantee you're starting from the same version.

It would be great if you could set up Hub to also autobuild based on repo tag (this is an option in the Type dropdown on the Build Settings tab in Hub) and then add version tags to this repo (v0.1, v0.2).

This isn't an official Docker request, just asking because we're using this container and it would make deploying it more deterministic. Thanks!

**Comment by 3h4x** [comment]
Just right now pods on our infrastructure were crashing because path to the config has changed.
This would be greatly appreciated!

**Comment by bakhti** [comment]
@discordianfish #75 seems to be a duplication of this one

**Comment by discordianfish** [comment]
Agree, this should be fixed. I think though this should be switched to a similar cicircle based build setup like prometheus. I've added the tag selector to the docker hub builds for now but not sure it works. I don't get their UI.

**Comment by sebastiangraf** [comment]
For me, it looks like it is fixed: Tags for docker images are now existing.

Thanks a lot for the fix, in combination with #115 it really became necessary.

**Comment by nenych** [comment]
Create please version tag for current latest.
Thanks.

**Comment by brian-brazil** [comment]
Sounds like it's fixed.
