### ISSUE TITLE
Export data to use in a graph

### ISSUE THREAD

**Issue by roelywoely** [prometheus/cloudwatch_exporter#59]
Not an issue, but it's more a question.
Currently when a specific event occurs in my application, a metric is recorded in CloudWatch with the value of 1.
I have thousands of events a day. And I want to display graph data about how many times this event occurs per hour (or per day) in Prometheus.
I thought I could use this tool for that, but I only see a single value per dimension (as stated in the docs: a gauge). Am I doing something wrong?

**Comment by brian-brazil** [comment]
I'm not familiar enough with that part of CloudWatch to say, we just pull in what data CloudWatch provides to us.

In general I'd recommend directly instrumenting your application with one of our client libraries and having Prometheus scrape them directly.
