### ISSUE TITLE
[bug]: AWS/ES metrics not able to get pleasee help ,urgent!

### ISSUE THREAD

**Issue by raman0914** [prometheus/cloudwatch_exporter#593]
I'm not able to extract AWS/ES metrics from cloudwatch .

can anyone please provide me any demo on how he have done it.

I tried with

`- aws_namespace: AWS/ES
aws_metric_name: ClusterStatus.yellow
aws_statistics: [ Average ]
aws_dimensions: [ DomainName,ClientId ]`

i tried below one in cli, i'm able to get metrics in cli but not in prometheus through exporter.

<img width="912" alt="Screenshot 2023-10-18 at 11 18 44 PM" src="https://github.com/prometheus/cloudwatch_exporter/assets/50668589/f0cb3f87-df2f-4181-840d-e4a2aedc7e91">

For other namespaces, it is working fine. but i'm not able to do it for AWS/ES. not sure what wrong i'm doing.

i really need help. i'm stuck in it. I have seen one discussions on this, but that also didn't work. Is there any example file something like Elastic search.yaml, that i can refer.

Please suggest....!!

**Comment by raman0914** [comment]
```
 - aws_namespace: AWS/ES
aws_metric_name: ClusterStatus.yellow
aws_statistics: [ Average ]
aws_dimensions: [ DomainName,ClientId ]
```

This is what i tried in config.yml, yet it not worked

**Comment by raman0914** [comment]
Also , i'm using v0.15.3 verison

**Comment by Lincon-Freitas** [comment]
I'm having the same problem running on version 0.15.4

**Comment by raman0914** [comment]
It worked for me bro,

try specifying only these with your aws configurations

```
- aws_namespace: AWS/ES
  aws_metric_name: ClusterStatus.yellow
  aws_statistics: [ Average ]
  aws_dimensions: [ DomainName,ClientId ]
```
  
  don't use aws_dimesion_select.
  
 and 1 more important , i tried rollout restart for my k8s where i deployed this as docker image. These two tricks worked for me.

**Comment by Lincon-Freitas** [comment]
Yeah it worked, thanks! I guess you can close the issue then.
