### ISSUE TITLE
Expose period_seconds as a metric

### ISSUE THREAD

**Issue by smelchior** [prometheus/cloudwatch_exporter#62]
I am currently exporting some DynamoDB metrics with the exporter:
```     
     - aws_namespace: AWS/DynamoDB
       aws_metric_name: ConsumedReadCapacityUnits
       aws_dimensions: [Tablename]
       aws_statistics: [Sum]
     - aws_namespace: AWS/DynamoDB
       aws_metric_name: ConsumedWriteCapacityUnits
       aws_dimensions: [TableName]
       aws_statistics: [Sum]
```

In my charts i actually want to display the average amount of consumed capacity. Unfortunately just pulling the average value for these metrics from cloudwatch is not really helpful, as this gives incorrect data.
In my charts i now have to divide the Sum value by the period_seconds value (600 for my case). As this might change, it would be very helpful to have the period_seconds exposed as a metric to use it in the grafana dashboards.

**Comment by brian-brazil** [comment]
Having this for every single metric would seem a bit unwieldy.

The general presumption in Prometheus is that you know what your scrape/eval intervals are, and I would argue the same for the cloudwatch exporter settings.

**Comment by smelchior** [comment]
Well the period_seconds is usually a global setting right? so this would usually only be a single value? 
The problem is, that if i change the value, my long-term charts will show incorrect values as i have to change the static divisor.

**Comment by brian-brazil** [comment]
It's both a global default and per-metric.

You only need to change it for a few specific metrics, like S3.

**Comment by smelchior** [comment]
Ok, i understand. So only exposing the global value + a value for each metric where it has been customised is not an option? That should not bloat the output too much. I know, my use case is a bit special, but it would be nice if it could be covered :-)

**Comment by brian-brazil** [comment]
It'd be a bit too much, for a problem you shouldn't really be having.

I'd suggest just hardcoding the value elsewhere, as period_seconds isn't something you usually change.

**Comment by smelchior** [comment]
ok, we do change it a couple of times to optimise costs for cloudwatch retrievals, but i can why you would not want to add this.

**Comment by brian-brazil** [comment]
The general recommendation is not to use the cloudwatch exporter unless you don't have another choice (e.g. ELBs).

The retention on Cloudwatch has also increased to 13 months, so if you're just pulling data into Prometheus to have to beyond the previous 2w. Grafana can also pull straight from Cloudwatch if you're just looking for graphs.

**Comment by smelchior** [comment]
Good point, i tried using CloudWatch directly, but it does not support wildcard matches for the metrics. So i cannot display the data for all dynamodb tables named ^foo.+$ in one graph and i have to select everything separately. With the data from prometheus that is possible :-)

**Comment by brian-brazil** [comment]
Sounds like a feature request for Grafana.

**Comment by smelchior** [comment]
Oh it [exists](https://github.com/grafana/grafana/issues/7530) already but it is more of an AWS Cloudwatch API issue.
