### ISSUE TITLE
Getting metrics for dead ELBs might cost a lot of money

### ISSUE THREAD

**Issue by moshebs** [prometheus/cloudwatch_exporter#64]
This might be also relative to other resources, but I felt the pain with ELBs.

Consider the following configuration:

 - aws_namespace: AWS/ELB
   aws_metric_name: UnHealthyHostCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select_regex:
     LoadBalancerName: [myELB-.*]

What happens in CloudWatchCollector is that ELBs that do not exist at the moment of scraping are also returned as part of the available metrics in the results of getDimensions(). Then the scrape() method calls an API per ELB and rules out the resources that have too old data points. You pay fr each API you call, so you just paid for an API that brought you metrics for an ELB that is dead already.

Imagine a development environment, where ELBs are constantly created and destroyed. The list gets longer with time and the costs go higher.

I handled this issue by forking the project and using the ELB API to filter out dead ELBs before the metrics API is called, and I will be happy to create a merge request for that, but the solution is specific to ELBs, and I guess the problem might be relevant to other resource types as well.

Thanks.

**Comment by brian-brazil** [comment]
Yes, there's many many resource types and this is fundamentally a Cloudwatch exporter rather than an AWS exporter.

For a dev environment I'd suggest using Cloudwatch directly. Since the increase in retention time there's not too much point in having the data in Prometheus unless you want to do some non-trivial alerting.

**Comment by rayj-pgi** [comment]
This helped me understand why I was seeing so many requests for so few ELBs

**Comment by rayj-pgi** [comment]
I've merged @moshebs change with the latest code.

https://github.com/PremiereGlobal/cloudwatch-exporter-elb

https://hub.docker.com/r/premiereglobal/cloudwatch-exporter-elb
