### ISSUE TITLE
Information about (any) Cryptographic Dependencies 

### ISSUE THREAD

**Issue by mamccorm** [prometheus/cloudwatch_exporter#640]
Hi there,

I am interested in understanding whether this project bundles its own cryptographic libraries or relies on the cryptographic libraries available on the host system (e.g., the Java Cryptography Architecture provided with the JDK).

From my own research it looks like the latter, but it would be good to get a confirmation. Reason - we're looking to enforce some security settings at the JDK level on our images, and was curious if these would be respected by cloudwatch_exporter, or ignored.

**Comment by matthiasr** [comment]
Your research is as good as mine 😄 We don't do anything explicitly here, but I am not sure what the AWS client libraries do.
