### ISSUE TITLE
We have SAP Hana [metrics]: available in CloudWatch but metrics stopped coming on dashboard

### ISSUE THREAD

**Issue by Xblade007** [prometheus/cloudwatch_exporter#653]
Error : [Unable to scrape Prometheus metrics, please review the prometheus configuration]

What to check and where to check configuration breakages.

**Comment by matthiasr** [comment]
Hi, evidently this is a problem between your Prometheus configuration and it cannot scrape metrics from the exporter, not something that the exporter can help you with directly.

Please review your Prometheus configuration, and if you still believe this is an issue with the exporter itself, reopen this issue with

* your exporter configuration
* what you see on the exporter's `/metrics` endpoint
* your Prometheus scrape configuration
* what you see in Prometheus (both the Table and Graph views)
* where exactly you see this error

**Comment by Xblade007** [comment]
Thanks for your reply
