### ISSUE TITLE
[request]: Add additional labels on scraper level

### ISSUE THREAD

**Issue by mpostument** [prometheus/cloudwatch_exporter#663]
## Use case. Why is this important?

Hello, i have multiple cloudwatch exporters running in the same eks cluster. But they are scraping metrics from different AWS account. And i don't have ability to identify from which AWS account i am using. Would be nice to have ability to define set of additional labels which is added to every metric available in cloudwatch scraper

Metric relabel on prometheus is not an option, because i am using auto discovery and not static scraping job 

## How do you think the new configuration should look like?

Example:

```yaml
extraLabels:
  account_name: AWSAccount1
  env: Prod
```

**Comment by matthiasr** [comment]
Server-side relabeling is still the correct way to do this. Presumably, Kubernetes knows which pod belongs to which AWS account, or it would randomly replace exporter pods for one account with another…?

You can use [relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) to turn Kubernetes labels and annotations into Prometheus labels, even with automatic discovery. For inspiration, read through the [example Prometheus configuration](https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-kubernetes.yml). If you are using the Prometheus Operator, it generates such configuration for you, and it can be very instructive to read through the configuration it constructs as well.
