### ISSUE TITLE
(Dockerfile) /config.yml breaks kubernetes!

### ISSUE THREAD

**Issue by iMartyn** [prometheus/cloudwatch_exporter#67]
You cannot mount a ConfigMap into a file, only a directory in kubernetes.

This means that you can only run your config for cloudwatch in a ConfigMap if you override the entrypoint!

This should be overridable by an environment variable and ideally you shouldn't force people to need a config file.

https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c

**Comment by cemo** [comment]
see #54

**Comment by brian-brazil** [comment]
You're free to create docker files that better suit your particular setup.

There is no way around a config file for this exporter.

**Comment by iMartyn** [comment]
Sure.  https://github.com/prometheus/cloudwatch_exporter/pull/68
