### ISSUE TITLE
Need cross-account support through IAM assume role policy between different aws accounts

### ISSUE THREAD

**Issue by Vaibhav-1995** [prometheus/cloudwatch_exporter#689]
In addition to https://github.com/prometheus/cloudwatch_exporter/issues/362

Do we have any possibility to consider this in next release?
It will be great if we have cross-account support!

**Comment by Vaibhav-1995** [comment]
Hi Team,

Do we have any update on this?

**Comment by matthiasr** [comment]
Please don't open new issues that duplicate existing ones.
