### ISSUE TITLE
Custom Metrics not being exported

### ISSUE THREAD

**Issue by jnmarquis** [prometheus/cloudwatch_exporter#69]
I´ve configured a Custom Cloudwatch Metric like this:
metrics:
``
- aws_namespace: Custom/PageStats
  aws_metric_name: Page_Generation_Time
  aws_statistics: [Average]
``

And its not being exported. 

Is this supported?

**Comment by brian-brazil** [comment]
Does it work from the aws cli?

**Comment by jnmarquis** [comment]
my bad. Correct configuration is (note no Custom):

aws_namespace: PageStats
aws_metric_name: Page_Generation_Time
aws_statistics: [Average]
``


Thanks a lot

**Comment by abc-dotcom** [comment]
Hello

I´ve configured a Custom Cloudwatch Metric like this: cwexpo_custom_metrics is my custom namespace. But metrics are not getting exported.
  aws_namespace: cwexpo_custom_metrics
  aws_metric_name: mem_used_percent
  aws_statistics: [Average]
  aws_dimensions: [InstanceId]
