### ISSUE TITLE
Bad idea to export label job

### ISSUE THREAD

**Issue by Rudd-O** [prometheus/cloudwatch_exporter#71]
Due to how relabeling works, job is not available during relabeling, so we as users cannot do anything with the label.  It cannot be mutated or copied into another label.  It simply appears as label exported_job into Prometheus master.

Suggest changing the name of the exported job label to "namespace" which is both more appropriate and does not conflict at all with the built in autolabeling of metrics.

Thanks.

**Comment by brian-brazil** [comment]
This use of the job label is appropriate, as cloudwatch jobs map well to Prometheus jobs. You're looking for honor labels.

**Comment by Rudd-O** [comment]
It's not appropriate because it cannot be remapped thru relabeling and because it conflicts with the job label, which by convention is operator-defined.

Honor_labels is for federation principally and it is documented that is a security risk to enable it just for regular exporters, as then they can impersonate other jobs.

Furthermore, as I explained already, the content of the label is the namespace prefix of the metrics.  This is not how job is meant to be used by convention.

Please conform to established convention, or we will have to fork.  Thank you in advance.

On August 31, 2017 7:03:21 PM GMT+02:00, Brian Brazil <notifications@github.com> wrote:
>This use of the job label is appropriate, as cloudwatch jobs map well
>to Prometheus jobs. You're looking for honor labels.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/prometheus/cloudwatch_exporter/issues/71#issuecomment-326359779

--

Rudd-O

http://rudd-o.com/

**Comment by brian-brazil** [comment]
> It's not appropriate because it cannot be remapped thru relabeling

Everything can be remapped through relabelling.

> which by convention is operator-defined.

That's a default, and not always what you want. Such as here.

> This is not how job is meant to be used by convention.

This is in line with how the job label is meant to be used. I'm the one behind that convention.

**Comment by Rudd-O** [comment]
> Everything can be remapped through relabelling.

I believe this contention is incorrect, because I just wasted two work hours trying to do so.  Relabeling from label `job` to another label copies whatever Prometheus sets as `job_name`.  Relabeling from label `exported_job` to another label copies nothing and therefore the relabel does not succeed.

> That's a default, and not always what you want. Such as here.

I am pretty sure I want my job name not to be dictated by the exporter, *in this specific case too*.

Please do not argue by trying to tell me what I want — I am in a better position to know that.

> This is in line with how the job label is meant to be used. I'm the one behind that convention.

Having metrics labeled `job=aws_ec2` when I have explicitly named the job `cloudwatch` is (a) nonsensical (b) worthless anyway, because the master automatically renames the metric to `exported_job` by default, and that label cannot be remapped (as I explained above).

For those reasons, I think you are incorrect about your belief that you are the one behind the convention in this case.

That said, you've made your case very clear — you do not seem to have any plans to have this exporter stop breaking convention, and it is a waste of my time to provide reasoned arguments to persuade you.

Therefore, I will fork, and perhaps publicize that fork.

**Comment by brian-brazil** [comment]
I think you want https://www.robustperception.io/relabel_configs-vs-metric_relabel_configs/

**Comment by Rudd-O** [comment]
While I remain unpersuaded that it's conventional to emit a `job` label by default in this exporter (no other exporter does that, and it complicates things unnecessarily)...

...I must say stand corrected about my incorrect method of relabeling configs and I thank you for your help in pointing it out.  Fork will not be necessary.

Again, thanks.
