### ISSUE TITLE
add a CMD instruction for the dockerfile like the `prom/prometheus` or `prom/alertmanger` containers

### ISSUE THREAD

**Issue by ajeeshpu** [prometheus/cloudwatch_exporter#72]

**Comment by ajeeshpu** [comment]
while building child images its necessary to have the config.yml in context since the onbuild performs an ADD
it will be nice to have a CMD option like the `prom/prometheus` or `prom/alertmanger` containers

**Comment by brian-brazil** [comment]
I believe #254 resolved this.
