### ISSUE TITLE
[bug]: cloudwatch_metrics_requested_total is not being properly incremented

### ISSUE THREAD

**Issue by emmanuelperotto** [prometheus/cloudwatch_exporter#742]
### What did you do

I'm sending a `GetMetricData` request with this `MetricDataQueries` 

```
MetricDataQueries=[
        {
            'Id': 'foo',
            'MetricStat': {
                'Metric': {
                    'Namespace': 'AWS/DynamoDB',
                    'MetricName': 'ConsumedWriteCapacityUnits',
                    'Dimensions': [
                        {'Name': 'TableName',
                         'Value': 'one-table'}
                    ]
                },
                'Period': 300,   # 5 minutes
                'Stat': 'Sum',
                'Unit': 'Count'
            },
            'ReturnData': True,
        },
        {
            'Id': 'bar',
            'MetricStat': {
                'Metric': {
                    'Namespace': 'AWS/DynamoDB',
                    'MetricName': 'ConsumedWriteCapacityUnits',
                    'Dimensions': [
                        {'Name': 'TableName',
                         'Value': 'another-table'}
                    ]
                },
                'Period': 300,   # 5 minutes
                'Stat': 'Sum',
                'Unit': 'Count'
            },
            'ReturnData': True,
        }
    ]
```

### What did you expect to see?

It is expected to increase by 2 the `cloudwatch_metrics_requested_total` given the `MetricDataQueries` size is 2.

### What did you see instead? Under which circumstances?
It incremented by 1 the metric `cloudwatch_metrics_requested_total`

### Are you currently working around this issue?

I've opened the PR to fix it
https://github.com/prometheus/cloudwatch_exporter/pull/741

### Additional context

How YACE increments this metric value: https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/clients/cloudwatch/v2/client.go#L117

### Environment

* Exporter version: `v0.15.5`
* Operating system & architecture: `Darwin Kernel Version 23.6.0` 
* Running in containers? y
* Using the official image? y

### Exporter configuration file

<details>
    <summary>expand</summary>

```yaml

```

</details>

### Logs

<details>
<summary>expand</summary>

```log
(paste log lines here)
```

</details>

**Comment by matthiasr** [comment]
Fixed in #741, thank you!
