### ISSUE TITLE
No tags in docker hub repo

### ISSUE THREAD

**Issue by no3am** [prometheus/cloudwatch_exporter#75]
I've noticed that the only existing tag in the docker hub repo is latest.
Can this be changed going forward to have proper tags that follow deployment.

In this case I downloaded the image, tagged it (as 0.5-SNAPSHOT) and pushed it to our own repo, if you create tags we'd be happy to use this tool directly from docker hub

**Comment by cassiomoreto** [comment]
do you guys have any update about this "almost 1-year-old" ticket?  😄

**Comment by zegl** [comment]
I'd also appreciate if if this project had stable tags on Docker Hub.

**Comment by fas3r** [comment]
any update ?

**Comment by bakhti** [comment]
Hey @discordianfish!
As I've understood from another issue, you've created and automated build on the docker hub. Would it be possible to add a new scenario of type Tag to it? Thanks.

**Comment by discordianfish** [comment]
@bakhti Thanks for the notice, correct - this is a dup of #53 so closing it.
