### ISSUE TITLE
Dynamic config reloading

### ISSUE THREAD

**Issue by alkalinecoffee** [prometheus/cloudwatch_exporter#77]
Any plans for this app to support reloading the config file during runtime, similar to prometheus' `curl -X POST http://127.0.0.1:443/-/reload` endpoint?

**Comment by brian-brazil** [comment]
Not currently.

**Comment by alkalinecoffee** [comment]
Java isn't my strongsuit, but I took a stab at this and will open a PR.

**Comment by fcgravalos** [comment]
> Any plans for this app to support reloading the config file during runtime, similar to prometheus' curl -X POST http://127.0.0.1:443/-/reload endpoint?

It's now supported, you can use the configmap-reload as a side-container if you are using any Docker scheduler
