### ISSUE TITLE
[request]: Service Quota Metrics

### ISSUE THREAD

**Issue by rfum** [prometheus/cloudwatch_exporter#771]
Hello, 
When I was checking the aws docs https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Quotas-Visualize-Alarms.html I realize that it's possible to have service quota metrics on cloudwatch. But I couldn't find anything related to service quota metrics in this repo. Do they natively supported? If not , are there any plan to support service quotas?

**Comment by HMEiding** [comment]
@matthiasr Could someone please have a look at this?

**Comment by matthiasr** [comment]
This exporter is generic – it doesn't really care about the underlying service, only CloudWatch, and tag manager, if you use the tag selection feature. As such, it should work with these metrics given the correct configuration. The main thing to get right is the dimensions; check the service documentation or the actual metrics for those. If in doubt, run the exporter in debug mode and it will show some extra messages about this.
For tag selection, the exporter also needs a way to map from the ARN returned by tag manager to a dimension on the metric. There's a default regular expression built in, but lately AWS has been getting more creative in their ARN formats.
The examples/ folder has a lot of configurations for other services that you can look at for inspiration. If possible, when you find a working configuration, please submit it there as well.
