### ISSUE TITLE
Is aws_dimensions really optional?

### ISSUE THREAD

**Issue by bryantrobbins** [prometheus/cloudwatch_exporter#80]
The README suggests that the aws_dimensions value is optional, but all examples include at least one dimension, and in the case of AWS/ApplicationELB, I received no metrics until a value of "LoadBalancer" was included.

If the value is "optional" in the sense that it is not required for every namespace, can this be clarified in the docs?

Cheers,
...Bryan

**Comment by brian-brazil** [comment]
It's optional per the Cloudwatch API docs.

**Comment by willastronomer** [comment]
I also found with EC2 metrics that without both aws_dimensions and aws_statistics it will fail
