### ISSUE TITLE
Push latest jar to maven.org

### ISSUE THREAD

**Issue by alkalinecoffee** [prometheus/cloudwatch_exporter#94]
Can we get the latest built jar pushed to maven.org?

Also it looks like the version has gone backwards, from 0.4.0 to 0.1.0 in the latest release.

**Comment by brian-brazil** [comment]
It was pushed: http://repo1.maven.org/maven2/io/prometheus/cloudwatch/cloudwatch_exporter/0.1.0/

**Comment by alkalinecoffee** [comment]
Thanks. I think the version downgrade threw me off.

<img width="1008" alt="screen shot 2018-03-14 at 5 32 21 pm" src="https://user-images.githubusercontent.com/1434559/37432117-b627ef32-27ad-11e8-9517-bdda69bdd741.png">
