### ISSUE TITLE
Exporting HTTPCode_Target_4XX_Count-type metrics

### ISSUE THREAD

**Issue by nielslaukens** [prometheus/cloudwatch_exporter#95]
I'm trying to export statistics about Application Load Balancers (ALBs) to Prometheus, but I'm having unwanted results.

I believe the core of the problem is the behaviour of HTTPCode_Target_4XX_Count-style metrics. As per [AWS documentation], these are only reported when there is a non-zero value. I believe the current behaviour boils down to the following:

* at time=`t1`, there is a 404 error.
* CloudWatch Metrics contains a metric for Timestamp=`t1`, Sum=1
* CloudWatch-exporter requests the metrics and [retains the most recent data point], exports that to Prometheus
* at time=`t2`, there are no more 404 errors
* CloudWatch Metrics contain no metric for Timestamp=`t2`
* CloudWatch-exporter requests the metrics and retains the most recent data point, which is still `t1`. Re-exports that to Prometheus.

The expected behaviour would be to export a value of `0` to Prometheus.

[AWS documentation]: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html
[retains the most recent data point]: https://github.com/prometheus/cloudwatch_exporter/blob/a1acb9efae2b39eef2981e05919ea7c97b78591c/src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java#L367

This is probably more complicated that it seems, since this is specific for these types of Metrics (most other metrics are always reported). Also, we'd need to cross-compare the "most recent" timestamp to these of other, related metrics (such as RequestCount, which may not even be requested by the user) to figure out if we simply don't have the data (yet), or that is should be zero-filled.

Are there any known workarounds for this issue? Or are there planned solutions?

Note that this is *not* related to Issue #22, although solving #22 will alter the behaviour of this issue: The "old" data-point will not be extrapolated anymore, but the data will be marked stale and not contain zero's.

**Comment by brian-brazil** [comment]
We can only export things that cloudwatch provides to us, it cloudwatch tells us there is nothing then we can only expose nothing. This is a fundamental problem with cloudwatch, there's not much we can do about it.
