### ISSUE TITLE
Very long scrape duration

### ISSUE THREAD

**Issue by radiating** [prometheus/cloudwatch_exporter#97]
Hello,

I'm running cloudwatch_exporter on a t2.medium EC2 instance (2vCPU, 4GB Mem), scraping about 100 cloudwatch metrics. The scrape duration is 25 seconds, which seem very long. This translates to the scrape timeout interval to be greater than 25 seconds in my Prometheus config file. Is the CW exporter scrape duration normally this long? Thanks!

```
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 24.848950703
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total 5640.0
```

**Comment by brian-brazil** [comment]
Cloudwatch can be slow, make sure the exporter is running in the region you're talking to.

**Comment by bboreham** [comment]
Could we have cloudwatch_exporter pull data on its own schedule, then answer a Prometheus scrape asynchronously from the latest data it has in memory?

This would also help in situations where you have >1 Prometheus scraping the same exporter.

**Comment by brian-brazil** [comment]
That's against the general exporter architecture, scheduling is the concern of Prometheus and not the role of exporters.

**Comment by lyonssp** [comment]
Wanted to comment on the numbers here, as I'm seeing similar behavior with many more metrics --

Is it normal to have the exporter make nearly 6k requests for 100 metrics?  I have about 20k metrics and am seeing a number on the order of 500-600k requests being made to cloudwatch.  

@brian-brazil  Do you have an explanation for how this request count scales with the number of metrics?
